### PR TITLE
Test cases for table components

### PR DESCRIPTION
**Pull request by KumarNayan**
Added test cases covering all points for TableComponent

closes [#1167](https://github.com/stakwork/sphinx-tribes/issues/1167)

New test cases

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by KumarNayan** [comment]
@ecurrencyhodler waiting for the review ?

**Comment by elraphty** [comment]
> #1167

Looking at it

**Comment by elraphty** [comment]
Looks good to me @ecurrencyhodler, merging.

**Comment by KumarNayan** [comment]
Thanks @elraphty .

**Pull request merged**
