### PR TITLE
Width when adding a user to an org is initially incorrect fix

### PR DESCRIPTION
**Pull request by Khaalid-oh**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

https://github.com/stakwork/sphinx-tribes/assets/84248666/009f8c70-71cb-4c0f-b2a9-08a418a67d20

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@Khaalid-oh I'm going to unassign you from two of your tickets. 

I want you to focus just on the unit test ticket. https://github.com/stakwork/sphinx-tribes/issues/996. 

If you do a good job of that one, we will assign you more bounties. 

Make sure your PR is clean, code actually addresses the ticket, and includes the ticket it's addressing.

As an incentive, I will add another 100k to the unit test ticket to offset the work you've put in for the other two bounties.

If you don't wish to take the unit test bounty, let me know and I can assign it to someone else.

**Comment by Khaalid-oh** [comment]
> @Khaalid-oh I'm going to unassign you from two of your tickets.
> 
> I want you to focus just on the unit test ticket. #996.
> 
> If you do a good job of that one, we will assign you more bounties.
> 
> Make sure your PR is clean, code actually addresses the ticket, and includes the ticket it's addressing.
> 
> As an incentive, I will add another 100k to the unit test ticket to offset the work you've put in for the other two bounties.
> 
> If you don't wish to take the unit test bounty, let me know and I can assign it to someone else.

I deleted the previous branch and created a new branch to address this issue. The reason the test is failing is because the jest config is not specified for src folder. It took a while for me to figure that out and that's why I have more than one PR, if you think there's no need for me to proceed with the fix I can move on to other project, I trust your judgment.

**Comment by Khaalid-oh** [comment]
> Focus on the unit test bounty I mentioned above. If you can complete that, we will assign more bounties to you. How does that sound?

Not a problem, I'll get on with that. 
Just to be sure: The [Fix glitch when moving from a tab on my profile to default profile view] fix seems to be approved,  you don't want me to push that as well ?

**Comment by ecurrencyhodler** [comment]
There's still a check failing and a messy commit history so it is not approved.

**Comment by Khaalid-oh** [comment]
> There's still a check failing and a messy commit history so it is not approved. 

I submitted a clean PR for the Bounty Unit Test with all check passed. Do you want to give me another shot at this on a new PR?

**Comment by ecurrencyhodler** [comment]
No. We are going to assign this to someone else. 

I will assign you another bounty once the unit test pr has been merged.

**Comment by Khaalid-oh** [comment]
> No. We are going to assign this to someone else. 
> 
> I will assign you another bounty once the unit test pr has been merged. 

Alright

**Pull request closed without merging**
