### PR TITLE
feat: description box for org home page

### PR DESCRIPTION
**Pull request by Khaalid-oh**
Screenshot 2024-01-22 at 15 50 34
## [Issue ticket number and link
](https://github.com/stakwork/sphinx-tribes/issues/1318)
## UI Implementation

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@Khaalid-oh some jest tests are failing. Can you address that?

**Comment by Khaalid-oh** [comment]
> @Khaalid-oh some jest tests are failing. Can you address that?

I commented out my code and ran the test and those tests are still failing

**Comment by ecurrencyhodler** [comment]
Have you tried rebasing?

**Comment by Khaalid-oh** [comment]
I ran the test on the master branch without my changes and those tests were still failing actually

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

Also raph is fixing the tests you pointed out. Thanks for raising that.

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Pull request closed without merging**
