### PR TITLE
Removed description img code from bounty desc

### LINKED ISSUE #1242: Remove image from bounty that is being displayed on the home page
**Describe the bug**
The image inside the bounty and github issue is being displayed on the home page.

https://community.sphinx.chat/bounty/1033

Screenshot 2024-01-03 at 1 08 40 PM

**Expected behavior**
The image should not be displayed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot of the fix

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes
Removed the description image code from the Bounty Header. Could not find any other place where description image was getting affected by removing this part of code.

## Issue ticket number and link
Closes #1242 

## Type of change
Before:

image

After:

image

https://github.com/stakwork/sphinx-tribes/assets/91251535/64ba9d53-f0c6-45e6-995c-26191879bbcf

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by VividhPandey003** [comment]
I would need a code review for this. I am quite not sure if this is was the change you had on your mind.

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 can you post a video of you click on the bounty? We ran into a similar issue last time where the image wasn't displayed inside the bounty page.

**Comment by VividhPandey003** [comment]
Okay yes. On it

**Comment by VividhPandey003** [comment]
@ecurrencyhodler I've updated the pr description with a video.

**Comment by ecurrencyhodler** [comment]
Thanks the video and screenshots lgtm. Yeah let's get a code review. Good work.

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
