### PR TITLE
chore: auto mock db instance

### LINKED ISSUE #1214: Auto mock db
On a different topic @kevkevinpal  can i do some refactoring of the handlers to make it more testable ? **if i get assigned this bounty** . 

Mainly would keep all the handler functions behind a struct and inject httpClient to it, making it much more easier to replace it with mockClient at the test. Something like this [handler.go](https://github.com/anish-yadav/lms-api/blob/main/internal/user/handler/http.go#L18).

In the future can create an interface for DB and inject it in the handler thereby making the handler unit much more testable.
Can use [mockery](https://github.com/vektra/mockery)  to auto generate mocks to cover all scenario and inject the mocks in tests thereby reducing our error to create mock functions and all.

Just a thought.

_Originally posted by @wright-eric in https://github.com/stakwork/sphinx-tribes/issues/1208#issuecomment-1872173900_

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
used mockery to auto create mocks for db

## Issue ticket number and link
closes #1214 

## Type of change
unit test

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by wright-eric** [comment]
cc @wright-eric  @ecurrencyhodler

**Comment by kevkevinpal** [comment]
@wright-eric what are the steps to add new mocks to `db/mocks` when new functions are added I am not familiar with mockery maybe modifying the README.md or adding a doc would be helpful

**Comment by wright-eric** [comment]
> @wright-eric what are the steps to add new mocks to `db/mocks` when new functions are added I am not familiar with mockery maybe modifying the README.md or adding a doc would be helpful

sorry didnt add the doc before. I have now changed the ready with the detailed steps on using mockery. Should be straightforward and hope this helps with other tests as well.

**Comment by elraphty** [comment]
@wright-eric can you add how to install mockery in the README I installed on Mac using ```brew install mockery```

**Comment by wright-eric** [comment]
updated the docs with steps to install mockery using different ways, also linked the mockery documentation link in case for more docs.

**Comment by elraphty** [comment]
> updated the docs with steps to install mockery using different ways, also linked the mockery documentation link in case for more docs.

Thanks

**Comment by elraphty** [comment]
@kevkevinpal it looks good to me, I tried using mockery and it generates the mock db, merging.

**Comment by ecurrencyhodler** [comment]
paid!

**Pull request merged**
