### PR TITLE
Fix Org Image Upload

### LINKED ISSUE #1068: Unable to upload a picture to an organization even with right permissions
**Describe the bug**
I'm unable to upload a picture to an organization even with right permissions. In the video below, I am the admin of the org.

https://github.com/stakwork/sphinx-tribes/assets/32662508/3b3cafb7-d0a7-4f86-855f-9d535e6dd640

**Expected behavior**
I should be able to upload the image.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of this working

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

Moved the token refresh to App.tsx to enable token refresh in child components

## Issue ticket number and link

Closes #1068

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device

### CODE REVIEW

**Comment by kevkevinpal** [comment]
you might want to remove `frontend/app/coverage` from the diff

we should remove it from the project in general to be honest

**Comment by elraphty** [comment]
> you might want to remove `frontend/app/coverage` from the diff
> 
> we should remove it from the project in general to be honest

Oh! thanks, I was wondering what must have changed.

**Comment by ecurrencyhodler** [comment]
I still can't update photo in sphinx app org even though i have the right perms.

**Comment by elraphty** [comment]
> I still can't update the photo in sphinx app org even though I have the right perms.
Just tried I can't seem to click on the edit button for Sphinx App ORg, can you give me the right permissions so I can try uploading from my end?

**Comment by ecurrencyhodler** [comment]
@elraphty I'm going to add you to a different org. try on "sphinx demo org".

**Comment by elraphty** [comment]
> @elraphty I'm going to add you to a different org. try on "sphinx demo org".

It's working now.

**Pull request merged**
