### PR TITLE
New Org home page

### PR DESCRIPTION
**Pull request by Vayras**
This PR implements the new org home page 
The UI has been tested on chrome
jest based test has been added
loom video:
https://www.loom.com/share/3c513000b80c40cea7a94c41f50f45f4?sid=62418d1b-0885-444b-abbf-06328fcc160b

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Great work. Thanks for being quick with this. In the future make sure to tie the specific issue you are addressing to the PR: https://github.com/stakwork/sphinx-tribes/issues/1312

Let's get a code review.

**Comment by Vayras** [comment]
> Great work. Thanks for being quick with this. In the future make sure to tie the specific issue you are addressing to the PR: #1312
> 
> Let's get a code review.

sure will do

**Comment by elraphty** [comment]
@Vayras, add data to the status, skills, and sort by dropdowns, get the values from the bounties homepage filters, and also enable the search input, I can type in the search input at the moment, thanks.

**Comment by Vayras** [comment]
> @Vayras, add data to the status, skills, and sort by dropdowns, get the values from the bounties homepage filters, and also enable the search input, I can type in the search input at the moment, thanks.

it was not mentioned in the original issue and it was mentioned to disable the search as all of that will be fixed in separate PR #1322, I think but I will add it

**Comment by Vayras** [comment]
> > @Vayras, add data to the status, skills, and sort by dropdowns, get the values from the bounties homepage filters, and also enable the search input, I can type in the search input at the moment, thanks.
> 
> it was not mentioned in the original issue and it was mentioned to disable the search as all of that will be fixed in separate PR as mentioned in #1322 I think, but I can add it

**Comment by ecurrencyhodler** [comment]
Hey @elraphty those aren't scoped for this issue. Those features will be handled in other bounties. Can you review his code as is?

**Comment by ecurrencyhodler** [comment]
Tested and paid!

**Pull request merged**
