### PR TITLE
Fix/button design

### PR DESCRIPTION
**Pull request by AmitPaliwal-rs**
1. Fixed Button design
2. Replace pictures with GIF in startup modal.

### CODE REVIEW

**Comment by kevkevinpal** [comment]
talked with Milan think he said he wanted the font `Barlow` in the button

**Comment by AmitPaliwal-rs** [comment]
I've made a note of applying the correct font and improvements to the search bar as per today's discussion. I can push that in this PR itself tomorrow or create a new PR if this one is merged.

**Comment by kevkevinpal** [comment]
> I've made a note of applying the correct font and improvements to the search bar as per today's discussion. I can push that in this PR itself tomorrow or create a new PR if this one is merged.

awesome I can just keep this one up and merge it tomorrow

**Comment by AmitPaliwal-rs** [comment]
fixed fonts and made improvements to the search bar. 
some minor work is pending on search bar icon, so please merge this tomorrow once I push the search bar update.

**Comment by kevkevinpal** [comment]
> fixed fonts and made improvements to the search bar. some minor work is pending on search bar icon, so please merge this tomorrow once I push the search bar update.

sounds good I can publish this on people-test.sphinx.chat so milan can see the progress so far but I'll keep the PR up

**Pull request merged**
