### PR TITLE
  created custom date filter for superadmin page 

### PR DESCRIPTION
**Pull request by vishnu552**
[https://www.loom.com/share/834ddefaf06548b7bbd615d3df2a825b](url)

  created custom date filter for superadmin page 
fixes:#1009

### CODE REVIEW

**Comment by vishnu552** [comment]
@elraphty ok, thanks

**Comment by elraphty** [comment]
@vishnu552 make the current date the default date, I have to click on other dates before I can click the current date. [Watch the loom video to see](https://www.loom.com/share/93caa86a33254848b591097e1e437fe1)

**Comment by elraphty** [comment]
> @elraphty ok,I'll fix it

thanks

**Comment by ecurrencyhodler** [comment]
Paid! I reduced the bounty 100k because you didn't implement the manual typing of the dates.

**Comment by vishnu552** [comment]
@ecurrencyhodler  thank you, it was nice experience working with this community.

**Pull request merged**
