### PR TITLE
fix(#1137): Display created bounty after successful bounty creation

### LINKED ISSUE #1137: Display created bounty after successful bounty creation
### Context
When I create a bounty, i should be displayed the bounty if it has been successfully created. 

Currently our website does not do this.

https://github.com/stakwork/sphinx-tribes/assets/32662508/33652560-19a8-4489-9fc9-911a6f1a4e2b

### Expected behavior
Let's say I created a bounty titled: Show count next to ticket status in filter

I should see this bounty page immediately after finishing clicking "finish". This is true for both assigned and unassigned created bounties.

Screenshot 2023-12-18 at 4 11 41 PM

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created a component test that the bounty page modal appears after bounty has been created. Here is an example of a component [test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by Vayras**
With This pull request changes made are:
Now when you post a bounty you are redirected to the created bounty page as required by the issue #1137

The fix : get the current bounty index from api and use the data to redirect to created bounty page

video 

https://github.com/stakwork/sphinx-tribes/assets/89837102/07093217-cbfc-4450-b3a1-74b2fcc8846f

This has been Tested on Chrome and Firefox
fixes #1137

### CODE REVIEW

**Comment by kevkevinpal** [comment]
is there anyway to not make the page reload to get the new bounty?

**Comment by kevkevinpal** [comment]
rebased to master for you [f1daccf](https://github.com/stakwork/sphinx-tribes/pull/1191/commits/f1daccfe6ea96af015ed6514acef42b9fa1e6fe1)

**Comment by Vayras** [comment]
> is there anyway to not make the page reload to get the new bounty?

@kevkevinpal  Yeah If I remove the await window.location.reload(); it would still work fine  and no reloads

**Comment by kevkevinpal** [comment]
> > is there anyway to not make the page reload to get the new bounty?
> 
> @kevkevinpal Yeah If I remove the await window.location.reload(); it would still work fine and no reloads

nice can you make that change I think that would work better

**Comment by Vayras** [comment]
> > > is there anyway to not make the page reload to get the new bounty?
> > 
> > 
> > @kevkevinpal Yeah If I remove the await window.location.reload(); it would still work fine and no reloads
> 
> nice can you make that change I think that would work better

@kevkevinpal removed the reload

**Comment by ecurrencyhodler** [comment]
Tested and this works nicely. Will pay you once we get our org funded. Good work.

**Pull request merged**
