### PR TITLE
Refactor TestCreateConnectionCode To Use A Real Postgres DB For The Test

### PR DESCRIPTION
**Pull request by Shoaibdev7**
## Describe your changes

image

## Issue ticket number and link

Closes: #1730

## Checklist before requesting a review
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Shoaibdev7** [comment]
Hi @elraphty, I face this issue:
image

**Comment by elraphty** [comment]
@Shoaibdev7 your tests are failing

**Comment by elraphty** [comment]
> Hi @elraphty, I face this issue: image

The error only occurs when a variable is used that has no address in the memory

**Comment by Shoaibdev7** [comment]
Hi @elraphty, Please approval the workflows. I have fixed

**Pull request merged**
