### PR TITLE
Fix glitch when moving from a tab on profile to default profile view 

### PR DESCRIPTION
**Pull request by Khaalid-oh**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

https://github.com/stakwork/sphinx-tribes/assets/84248666/23527605-0887-4b73-a05a-549652492486

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hey @Khaalid-oh . The video recording looks like the glitch is still there. Can you take another look?

**Comment by Khaalid-oh** [comment]
> Hey @Khaalid-oh . The video recording looks like the glitch is still there. Can you take another look?

The glitch you are reffering to is not the peopleList that pops out for a while on the user profile?

**Comment by ecurrencyhodler** [comment]
Actually you're right. I looked at the behavior of other tabs and they display a similar loading behavior before displaying the info. 

Have you tested clicking on all the tabs to make sure nothing is broken?

And can you test looking at a profile that isn't yours so that the people list DOES appear both from a signed in and signed out perspective?

**Comment by Khaalid-oh** [comment]
> Actually you're right. I looked at the behavior of other tabs and they display a similar loading behavior before displaying the info.
> 
> Have you tested clicking on all the tabs to make sure nothing is broken?
> 
> And can you test looking at a profile that isn't yours so that the people list DOES appear both from a signed in and signed out perspective?

Yes, I've done that. I'll send a video testing all that as well

**Comment by Khaalid-oh** [comment]
> > Actually you're right. I looked at the behavior of other tabs and they display a similar loading behavior before displaying the info.
> > Have you tested clicking on all the tabs to make sure nothing is broken?
> > And can you test looking at a profile that isn't yours so that the people list DOES appear both from a signed in and signed out perspective?
> 
> Yes, I've done that. I'll send a video testing all that as well


https://github.com/stakwork/sphinx-tribes/assets/84248666/a099df8b-0b4a-436e-bbf8-8a21d4d10694

**Comment by ecurrencyhodler** [comment]
Perfect ty. Let's get a code review.

**Comment by kevkevinpal** [comment]
@Khaalid-oh did you make any changes?

**Comment by kevkevinpal** [comment]
closing this as I'm seeing no changes committed other than config changes and a yarn.lock update

**Comment by Khaalid-oh** [comment]
> closing this as I'm seeing no changes committed other than config changes and a yarn.lock update

SHA: bb0376ce021f5ed8be0993611a7a08cd6fbafdf7

**Comment by Khaalid-oh** [comment]
> closing this as I'm seeing no changes committed other than config changes and a yarn.lock update

There are changes  made to [UserInfoDesktopView]
SHA: bb0376ce021f5ed8be0993611a7a08cd6fbafdf7

**Comment by kevkevinpal** [comment]
I'm not seeing any changes to UserInfoDesktopView other than spacing changes in bb0376c

**Comment by Khaalid-oh** [comment]
> I'm not seeing any changes to UserInfoDesktopView other than spacing changes in [bb0376c](https://github.com/stakwork/sphinx-tribes/commit/bb0376ce021f5ed8be0993611a7a08cd6fbafdf7)

SHA: bb0376ce021f5ed8be0993611a7a08cd6fbafdf7

please check PersonPage.tsx

**Comment by kevkevinpal** [comment]
> > I'm not seeing any changes to UserInfoDesktopView other than spacing changes in [bb0376c](https://github.com/stakwork/sphinx-tribes/commit/bb0376ce021f5ed8be0993611a7a08cd6fbafdf7)
> 
> SHA: [bb0376c](https://github.com/stakwork/sphinx-tribes/commit/bb0376ce021f5ed8be0993611a7a08cd6fbafdf7)
> 
> please check PersonPage.tsx

swapping two args in an and statement doesn't change the result of the and statement that change does nothing

**Pull request closed without merging**
