### PR TITLE
[Unit Test] Added unit test for create or edit bounty handler

### LINKED ISSUE #1129: [Unit Test][Golang] CreateOrEditBounty
### Task:
1). create a new file in `/handlers/bounty_test.go` you can use `/handlers/auth_test.go` as a template
2). create unit test for golang function `CreateOrEditBounty` https://github.com/stakwork/sphinx-tribes/blob/master/handlers/bounty.go#L121
3). you may need to edit `/db/db_mock.go` to setup mock responses for `CreateOrEditBounty`

### Acceptance Criteria:
golang code coverage is increased and `CreateOrEditBounty` handler now has coverage

### PR DESCRIPTION
**Pull request by anish-yadav**
## Describe your changes
Added unit test for CreateOrEdit bounty http handler

## Issue ticket number and link
closes #1129 

## Type of change
Unit test changes

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by anish-yadav** [comment]
@ecurrencyhodler  let me know if this looks good.

**Comment by ecurrencyhodler** [comment]
Let's get a code review with @elraphty or @kevkevinpal

**Comment by kevkevinpal** [comment]
looks like you added a good amount of coverage with this change
`Coverage: 3.2%` -> `Coverage: 4.6%`

**Comment by kevkevinpal** [comment]
weird looks like a different percent on the job will update accordingly

**Comment by wright-eric** [comment]
> looks like you added a good amount of coverage with this change `Coverage: 3.2%` -> `Coverage: 4.6%`

can add more if needed :)

**Comment by kevkevinpal** [comment]
> > looks like you added a good amount of coverage with this change `Coverage: 3.2%` -> `Coverage: 4.6%`
> 
> can add more if needed :) ps i am same guy @anish-yadav

I will make more testing issues and we can open more bounties for them :)

**Pull request merged**
