### PR TITLE
Implement GET Endpoint for Phase-Specific Tickets

### PR DESCRIPTION
**Pull request by aliraza556**
### Describe the chnages:
- Adds new GET endpoint to retrieve tickets by phase UUID with authentication, validation, and comprehensive test coverage

closes: #1972

## Issue ticket number and link:
- **Ticket Number:** [ 1972 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes-frontend/issues/1972 ]

### Evidence:

image

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] New feature (non-breaking change which adds functionality)
- [x] I have provided a screenshot of changes in my PR

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @humansinstitute, @elraphty, Please review this PR.

**Comment by tobi-bams** [comment]
@aliraza556 please can you help review this conflict

**Comment by aliraza556** [comment]
> @aliraza556 please can you help review this conflict

@tobi-bams, Done

**Comment by elraphty** [comment]
Looks good to me, I will merged when the test passes

**Pull request merged**
