### PR TITLE
Add bounty status

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
Added the bounty status 
## Issue ticket number and link
#1182
## Type of change
UI changes
Please delete options that are not relevant.
- [ ✅ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [✅  ] I have performed a self-review of my code
- [✅  ] I have tested on Chrome and Firefox
- [✅  ] I have tested on a mobile device
- [✅  ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

## Video

https://github.com/stakwork/sphinx-tribes/assets/20900042/99b4192c-d799-4c02-ac00-aa1b6d848983

https://github.com/stakwork/sphinx-tribes/assets/20900042/6278ef15-6ac1-4d29-92ca-c2fda832102e

Note: Please suggest any UI changes for closed I have added black color as that just popped in my mind.

### CODE REVIEW

**Comment by gouravmpk** [comment]
@ecurrencyhodler Please tell if you need more changes in this.

**Comment by ecurrencyhodler** [comment]
@gouravmpk I want to stay as close as possible to the desktop version. Let's change "Closed" -> "Completed"

Since the desktop doesn't have a color for open, let's try the following:
- Open: Blue
- Assigned: Green
- Completed: Purple

Screenshot 2023-12-25 at 7 51 58 AM

**Comment by ecurrencyhodler** [comment]
Also to complete #1182 you'll need to add this to when looking inside a bounty as well.

**Comment by gouravmpk** [comment]
> Also to complete #1182 you'll need to add this to when looking inside a bounty as well.

Its present I will update the video also replaced Closed --> Complete not Completed as It goes with Pill dimensions 
image
image

**Comment by ecurrencyhodler** [comment]
Okay. Post a video of seeing the status both on the home page and inside the bounty and then we can do a code review. Thanks for catching the pill dimension on "complete". That works.

**Comment by gouravmpk** [comment]
> Okay. Post a video of seeing the status both on the home page and inside the bounty and then we can do a code review. Thanks for catching the pill dimension on "complete". That works.

Posted New Video

**Comment by ecurrencyhodler** [comment]
Thanks @gouravmpk. The complete button is grey on the home page. Can we change it to purple to match the design on the home page?

**Comment by gouravmpk** [comment]
> Thanks @gouravmpk. The complete button is grey on the home page. Can we change it to purple to match the design on the home page?

It is the style for completed bounties, I can change it but I think that is pre-implemented by someone so you may need to discuss it with team

**Comment by ecurrencyhodler** [comment]
@gouravmpk If it won't affect the home page, let's change it to purple. If it does, then we can leave it as is.

**Comment by gouravmpk** [comment]
> @gouravmpk If it won't affect the home page, let's change it to purple. If it does, then we can leave it as is.

Okay I will try

**Comment by gouravmpk** [comment]
> @gouravmpk If it won't affect the home page, let's change it to purple. If it does, then we can leave it as is.

@ecurrencyhodler I think its not breaking home page so Removed it and added Snap Shot in description.

**Comment by ecurrencyhodler** [comment]
LGTM.  Let's do code review

**Comment by gouravmpk** [comment]
@ecurrencyhodler I have added the banner and found the bounty for something similar to what I was doing 
https://github.com/stakwork/sphinx-tribes/issues/1126
Below is the video showing the difference between the current version of mobile bounty and after changes version.

https://github.com/stakwork/sphinx-tribes/assets/20900042/5b867f19-2342-4df0-b779-f3e0dbe2a440

**Comment by ecurrencyhodler** [comment]
@gouravmpk great catch!! Thanks for doing that.

**Comment by elraphty** [comment]
@gouravmpk   can you add some padding to the assigned and complete button status, it looks too compact compared to the open button status.

**Comment by gouravmpk** [comment]
> @gouravmpk   can you add some padding to the assigned and complete button status, it looks too compact compared to the open button status.

I can but the Pill that is being used will change too it open will look more smaller if I do that.

**Comment by gouravmpk** [comment]
> @gouravmpk   can you add some padding to the assigned and complete button status, it looks too compact compared to the open button status.

I can but the Pill that is being used will change too it open will look more smaller if I do that.

**Comment by kevkevinpal** [comment]
I'm trying to run locally but I am not seeing the same results on my side

**Comment by kevkevinpal** [comment]
> @gouravmpk I want to stay as close as possible to the desktop version. Let's change "Closed" -> "Completed"
> 
> Since the desktop doesn't have a color for open, let's try the following:
> 
>     * Open: Blue
> 
>     * Assigned: Green
> 
>     * Completed: Purple
> 
> 
> Screenshot 2023-12-25 at 7 51 58 AM

fyi using blue and purple is a bad choice for ADA guidelines blue and purple get mixed in red-green color blindness which is pretty common

**Comment by gouravmpk** [comment]
@kevkevinpal are you running this branch ? https://github.com/gouravmpk/sphinx-tribes/tree/add-bounty-status

**Comment by kevkevinpal** [comment]
> > @gouravmpk I want to stay as close as possible to the desktop version. Let's change "Closed" -> "Completed"
> > Since the desktop doesn't have a color for open, let's try the following:
> > ```
> > * Open: Blue
> > 
> > * Assigned: Green
> > 
> > * Completed: Purple
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Screenshot 2023-12-25 at 7 51 58 AM
> 
> fyi using blue and purple is a bad choice for ADA guidelines blue and purple get mixed in red-green color blindness which is pretty common

I guess this comment can be ignored since we do have words on the pill aswell

**Comment by gouravmpk** [comment]
@kevkevinpal I think you are viewing Open bounties thats why assignee name is not showing up try Assigned or Completed bounties.

**Comment by ecurrencyhodler** [comment]
@kevkevinpal that's good feedback on blue/purple. But let's stay consistent with home page for now. We will prob do a redesign of home page where we can properly address a lot of the ux issues.

**Pull request merged**
