### PR TITLE
Fixed: Fix Issue with Organization Page Redirection on Bounty Home Page

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
when users click on an organization `(org)` link within the home page, they are redirected to a bounty-specific page in the same tab, which is not the intended behavior. Users expect to navigate to the organization's specific page with its bounties, and it should open in a new tab without redirecting the current page.

## Issue ticket number and link:
- **Ticket Number:** [ 1122 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes/issues/1122 ]

### Solution:
Implemented a new function `handleOrgPage` to handle the redirection. This function prevents the default action and propagation of the click event on the organization links, and then uses `window.open` to open the organization's specific bounties page in a new tab.

### Changes:
 - The `handleOrgPage` function now prevents default behavior and stops event propagation.
 - The function to include `event.preventDefault()` and `event.stopPropagation()` to prevent the default link behavior and stop event propagation.
 - It constructs the URL for the organization's page based on the organization's UUID.
 - The organization page is then opened in a new browser tab `(_blank)` when an organization is clicked.
 - This logic is implemented in a `<div>` element that wraps the `<OrganizationWrap>` component, ensuring that the entire organization element is clickable and leads to the correct page.

### Evidence:
Included is a video demonstration showing the corrected behavior. Now, when clicking on an organization's name on the bounty home page, a new tab opens with the organization's specific bounties, as intended.
**Video Link:** [ [https://www.loom.com/share/6504cfe7144e469c90bfb1cb03fc334c](url) ]

### Testing:
- Navigate to the home page.
- Click on any organization link.
- Verify that the organization's specific bounties page opens in a new tab.
- Ensure the original page remains intact and does not redirect or refresh.
- Manual testing across different devices and screen resolutions.
- Verified that no other functionalities are impacted by this change.

### Notes:
Please review the changes and merge this PR if everything is in order. This fix is essential for the upcoming release, and I look forward to any feedback you might have.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @kevkevinpal, @ecurrencyhodler 
I have fixed the Organization Page Redirection issue #1122. Could you take a look and provide your feedback?

**Comment by ecurrencyhodler** [comment]
Video checks out. Great work. Thanks for great documentation as well Ali! Let's get a code review

**Comment by kevkevinpal** [comment]
this was already fixed in

https://github.com/stakwork/sphinx-tribes/pull/1201

**Comment by ecurrencyhodler** [comment]
@aliraza556 I'm going to update the bounty to 100k sats for your work. Sorry for the mixup.

**Comment by aliraza556** [comment]
@ecurrencyhodler
Thank you so much for the update and the generous offer! I'm delighted to continue contributing to the project and appreciate your support.

**Pull request closed without merging**
