### PR TITLE
Fixed: Add Endpoints for Workspace Repositories

### PR DESCRIPTION
**Pull request by MirzaHanan**
## Describe your changes
- Add Endpoints for Workspace Repositories

close: #1624

## Issue ticket number and link:
- **Ticket Number:** [ 1624 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes/issues/1624 ]

### Evidence:
 - Please see the attached image as evidence.
 
image

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot

### CODE REVIEW

**Comment by MirzaHanan** [comment]
Hi @elraphty, @fvalentiner,
Please review this PR.

**Comment by fvalentiner** [comment]
> Hi @elraphty, @fvalentiner, Please review this PR.

Thank you @MirzaHanan! @elraphty is going to review it when he has a chance.

**Comment by MirzaHanan** [comment]
> > Hi @elraphty, @fvalentiner, Please review this PR.
> 
> Thank you @MirzaHanan! @elraphty is going to review it when he has a chance.

Thanks Sir!

**Comment by elraphty** [comment]
> Hi @elraphty, @fvalentiner, Please review this PR.

Looks good @MirzaHanan, but you were supposed to make a PR to this branch https://github.com/stakwork/sphinx-tribes/tree/feature-add-repos-to-workspaces, and not master. 

@fvalentiner did you ask him to make the PR to master?

**Comment by fvalentiner** [comment]
@elraphty no. @MirzaHanan please make the PR to the branch features-add-repos-to-workspaces
https://github.com/stakwork/sphinx-tribes/tree/feature-add-repos-to-workspaces

**Comment by MirzaHanan** [comment]
> @elraphty no. @MirzaHanan please make the PR to the branch features-add-repos-to-workspaces https://github.com/stakwork/sphinx-tribes/tree/feature-add-repos-to-workspaces

@elraphty, @fvalentiner,
Ok

**Comment by MirzaHanan** [comment]
Hi @fvalentiner, @elraphty,
Please review this PR.

**Pull request merged**
