### PR TITLE
Bug/people page right click - resolved

### LINKED ISSUE #1406: Enable opening a new tab by right clicking on the people page.
### Context
Currently, we are unable to right click to open a hunter profile in a new tab on the people page. But we can for right clicking on the home page. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/58c3afbf-cf7a-4d9f-b239-ca09c92a252b

Enable opening a new tab by right clicking like you see in the back half of the video.

Here's the PR that enabled right clicking on the home page that you can use for reference: https://github.com/stakwork/sphinx-tribes/pull/991

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a video
- [ ] I've created a test that asserts that when I right click, the correct menu opens

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by hritikmunde**
## Issue ticket number and link
closes #1406 

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

https://github.com/stakwork/sphinx-tribes/assets/46834595/931b6f96-6945-47f8-9e3e-a4445cb4e2fb

### CODE REVIEW

**Comment by hritikmunde** [comment]
Hi @ecurrencyhodler , the issue is resolved as shown in the video. I have also added highlights on the person card while hovering with the mouse arrow. The card was being treated as an image due to which there was no option to open in a new window. Now it is available. However, I had to use a dummy function called `showHighlights` for usestate which enabled the option to open in a new window.

**Comment by ecurrencyhodler** [comment]
Awesome. When you right click, are you opening the profile in a new tab?

**Comment by hritikmunde** [comment]
Yes its working

**Comment by ecurrencyhodler** [comment]
Okay let's get a code review. Gj!

**Comment by elraphty** [comment]
@hritikmunde your change messes up with the people card design, and also remove the hover color changePeople List

**Comment by hritikmunde** [comment]
Okay sure

**Comment by ecurrencyhodler** [comment]
all check pass. @elraphty can you take another look?

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by hritikmunde** [comment]
@ecurrencyhodler , yeah sure. Are you gonna create an issue for me to reference or should I just create a PR?

**Comment by ecurrencyhodler** [comment]
Create the PR but link to the same issue.

**Comment by hritikmunde** [comment]
okay will create a PR and link to this issue

**Comment by hritikmunde** [comment]
closing this PR

**Pull request closed without merging**
