### PR TITLE
Refactor TestCreateOrEditPerson UT

### PR DESCRIPTION
**Pull request by AhsanFarooqDev**
## Describe your changes

image

## Issue : #1709

close: #1709

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by AhsanFarooqDev** [comment]
@elraphty Please review

**Comment by elraphty** [comment]
@AhsanFarooqDev your test is failing due to duplicate keys, please change.

**Comment by AhsanFarooqDev** [comment]
@elraphty please approve workflows

**Comment by AhsanFarooqDev** [comment]
@elraphty please review PR

**Pull request merged**
