### PR TITLE
🐞Fix: Disable automatic close for bounty creation modal

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes/assets/91251535/daf24582-84cd-4f9a-8242-d4a4343e0e6f

Disabled automatic close for bounty creation modal

## Issue ticket number and link
Closes: #949

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please review this once.

**Comment by ecurrencyhodler** [comment]
Awesome! This looks great. Can you post another video of you highlighting a text and releasing the click outside the modal? There is an example video in the issue.

**Comment by VividhPandey003** [comment]
> Awesome! This looks great. Can you post another video of you highlighting a text and releasing the click outside the modal? There is an example video in the issue.

Sure, done. @ecurrencyhodler just updated the video, please review once

**Comment by kevkevinpal** [comment]
@VividhPandey003 are you in this tribe?

sphinx.chat://?action=tribe&uuid=Y_ztiSA6BkdxefwHkDZj1Pnp679A_M694ZGdTMOEbJRtEIdo5Bx6oVmFNVUtiOu6QPiJsA3IPrjNKppw6EeMuSw1A1p_&host=tribes.sphinx.chat

**Comment by VividhPandey003** [comment]
> @VividhPandey003 are you in this tribe?
> 
> sphinx.chat://?action=tribe&uuid=Y_ztiSA6BkdxefwHkDZj1Pnp679A_M694ZGdTMOEbJRtEIdo5Bx6oVmFNVUtiOu6QPiJsA3IPrjNKppw6EeMuSw1A1p_&host=tribes.sphinx.chat

@kevkevinpal BountyImprovementProg?

**Comment by kevkevinpal** [comment]
> > @VividhPandey003 are you in this tribe?
> > sphinx.chat://?action=tribe&uuid=Y_ztiSA6BkdxefwHkDZj1Pnp679A_M694ZGdTMOEbJRtEIdo5Bx6oVmFNVUtiOu6QPiJsA3IPrjNKppw6EeMuSw1A1p_&host=tribes.sphinx.chat
> 
> @kevkevinpal BountyImprovementProg?

nvm I see you now @coderturtle

**Comment by VividhPandey003** [comment]
> > > @VividhPandey003 are you in this tribe?
> > > sphinx.chat://?action=tribe&uuid=Y_ztiSA6BkdxefwHkDZj1Pnp679A_M694ZGdTMOEbJRtEIdo5Bx6oVmFNVUtiOu6QPiJsA3IPrjNKppw6EeMuSw1A1p_&host=tribes.sphinx.chat
> > 
> > 
> > @kevkevinpal BountyImprovementProg?
> 
> nvm I see you now @coderturtle

well **coderturtle is not my GithubUserId**, @kevkevinpal you might be tagging somebody else[nvm I see you now _at sign_ coderturtle]. Its just my sphinx id name. My github id is **VividhPandey003**

**Pull request merged**
