### PR TITLE
fix(ui): keep `searchText` in local storage

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes
Add `@persist` decorator to ui store's `searchText` field

## Issue ticket number and link
Fix: #1437

## Type of change

Bug fix (non-breaking change which fixes an issue)

https://jam.dev/c/972b9905-e5c8-41a5-a9fd-1515b9a74e75

### CODE REVIEW

**Comment by YLeight** [comment]
@ecurrencyhodler @elraphty This one is ready for test and review

**Comment by YLeight** [comment]
Micro fix

**Comment by ecurrencyhodler** [comment]
LGTM let's do a code review.

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat

**Comment by YLeight** [comment]
@ecurrencyhodler https://github.com/stakwork/sphinx-tribes-frontend/pull/6

**Pull request closed without merging**
