### PR TITLE
remove unneccessary arrow for edit or own bounty

### PR DESCRIPTION
**Pull request by Marvel-Ib**
## Describe your changes
this pr removes the next and prev arrow when viewing bounty in your profile and editing your bounty

## Issue ticket number and link
#632 

https://github.com/stakwork/sphinx-tribes/assets/44719946/a2dfd83e-b3ea-4f42-9f49-a3f290ca4e51

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

### CODE REVIEW

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler  @kevkevinpal

**Comment by ecurrencyhodler** [comment]
Thanks Marvel for submitting this pr! Can you edit the description of the PR to say "closes #632 "? This will automatically close the ticket once the pr has been merged.

**Comment by kevkevinpal** [comment]
lgtm nice work!

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib okay looks like this was only fixed for the component inside the profile. This should be applied to editing the front page of the bounty as well. Here's a video still showing the arrows. Would you mind also taking this on as well?

https://github.com/stakwork/sphinx-tribes/assets/32662508/5444ce14-0573-4dcf-b554-974172e091f9

**Comment by Marvel-Ib** [comment]
no problem. will take it on later today

**Comment by ecurrencyhodler** [comment]
Awesome! Okay will do. Will reach out via sphinx.

**Pull request merged**
