### PR TITLE
Fix: Removed "container" text on staging when looking at assigned tickets

### LINKED ISSUE #1047: Remove "container" text on staging when looking at assigned tickets
**Describe the bug**
For some reason I see the word "container" on assigned bounties on staging.
Screenshot 2023-12-05 at 2 39 08 PM

**Expected behavior**
The word should not appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

Removed "container" text 

output:
image

## Issue ticket number and link
Closes #1047 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Looks good to me! Let's get a code review even though it's a simple code change.

**Comment by ecurrencyhodler** [comment]
Actually eslint and prettier is failing. Can you check that?

**Comment by VividhPandey003** [comment]
> Actually eslint and prettier is failing. Can you check that?

on it

**Comment by VividhPandey003** [comment]
@ecurrencyhodler done with the checks. Thanks for being patient😄

**Comment by ecurrencyhodler** [comment]
Let's get a code review.

**Comment by ecurrencyhodler** [comment]
tested and I don't see it anymore. Paying you out. GJ!

**Pull request merged**
