### PR TITLE
fix #1274: Allows unpaid bounties to be displayed first

### LINKED ISSUE #1274: Add parameters to prioritize open bounties inside of profile for assigned bounties
### Context
Currently, bounties are listed chronologically regardless of status.
Bounties

We've gotten feedback from several hunters who said they would prefer to have open bounties first as it would help the locate bounties they need to work on first.

As a bounty provider, it would also help me keep track of open bounties as well. 

The fix is to add a parameter to the api call to prioritize open bounties call first. I'll create another issue to enable pagination in the backend to match the 20 displayed bounties under assigned bounties.

### Design
One simple and quick fix would be to simply show open bounties first like this:
Screenshot 2024-01-06 at 10 32 25 AM

### Acceptance Criteria
- [ ] I've tested on Chrome

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

Changed the sort direction to ASC.

## Issue ticket number and link

Close #1274

## Type of change

Backend one liner.

### CODE REVIEW

**Comment by VividhPandey003** [comment]
@elraphty Could you please review this once. This would fix the sort order we are facing right now.

**Comment by VividhPandey003** [comment]
> > @elraphty Could you please review this once. This would fix the sort order we are facing right now.
> 
> 
> 
> I have tested it a couple of times, it does not solve the issueImage Testting

Oh okay. I'll look into it

**Comment by VividhPandey003** [comment]
@elraphty Did you check that Assigned bounties display the unpaid Bounties first. The screenshot you've attached is of created Bounties. Could you check if the same sorting order is seen in assigned bounties because Created Bounties order is correct and what we need is for **Unpaid Assigned Bounties to be displayed first**

image
This is the current behaviour. Instead the unpaid bounties should be the first ones to be seen

**Comment by elraphty** [comment]
> @elraphty Did you check that Assigned bounties display the unpaid Bounties first. The screenshot you've attached is of created Bounties. Could you check if the same sorting order is seen in assigned bounties because Created Bounties order is correct and what we need is for **Unpaid Assigned Bounties to be displayed first**
> 
> image This is the current behaviour. Instead the unpaid bounties should be the first ones to be seen

Yeah, I checked both, create a couple of bounties and test again, you should be able to recreate it.

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Comment by VividhPandey003** [comment]
> Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

Yes I'll make a fix and push this as soon as possible.

**Pull request closed without merging**
