### PR TITLE
Implement bounty sort by newest and oldest

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
## Pull Request Description

- Implemented sort functionality by adding options to sort by newest and oldest
- Refactored the super admin logic by moving it into a reusable hook
- Extracted the `getBountyStatus` function into a utility folder, enhancing code organization. Additionally, tests have been added to ensure the correctness and reliability of the extracted function.

### Preview

https://www.loom.com/share/d8fd496cd9c645e4ba55dfaea29328a2?sid=baecdcdc-00dc-42fd-a755-9a968d65237e

### Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Looks like your prettier checks failed. Can you take a look?

**Comment by elraphty** [comment]
Please fix the prettier error by running `yarn run prettier` in `frontend/app` @Ekep-Obasi

**Comment by Ekep-Obasi** [comment]
@elraphty I keep running into this same issue where prettier validates locally but the workflow fails 

Capture

Please do you have a clue?

**Comment by Vayras** [comment]
@Ekep-Obasi can you run "yarn run prettier:check" and let me know the output you get in the console

**Comment by Ekep-Obasi** [comment]
> @Ekep-Obasi use "yarn run prettier" once , and check for the files changed in git and let me know , I see you have ran prettier:check and It has resulted in no errors

git status shows no changed file 
@Vayras thanks

**Comment by Vayras** [comment]
@Ekep-Obasi  I think the issue might be with the different prettier version between your local machine and on github here are some steps that might help you
1.Take the latest pull on your fork
2. "cd frontend/app" on your local machine
3. remove node modules "rm -rf node_modules"
4. run "npm i --legacy-peer-deps"
5. run "yarn install"
6. run "yarn run prettier now"

**Comment by elraphty** [comment]
> @elraphty I keep running into this same issue where prettier validates locally but the workflow fails
> 
> Capture
> 
> Please do you have a clue?

``` 
Rebase to the master branch
Delete your node_modoules and yarn.lock file
reinstall the modules, then run 
yarn run prettier in *frontend/app*
```

**Comment by Ekep-Obasi** [comment]
@elraphty @Vayras 
I have reinstalled prettier 
When I run prettier and check git, this is what I have `warning: LF will be replaced by CRLF`

**Comment by Vayras** [comment]
@Ekep-Obasi do you see files changed in the source control panel of vscode?

**Comment by Ekep-Obasi** [comment]
@Vayras @elraphty  Thank you for the help!

**Pull request closed without merging**
