### PR TITLE
fix: Make go order columns correctly in CSV export headers order in csv export

### LINKED ISSUE #1421: Make go order columns correctly in CSV export
### Context
Currently when I export the CSV from superadmin, the columns are ordered like this:
the order isn't correct.
Screenshot 2024-01-15 at 11 33 30 AM

This is the order it should be in:

- Date posted
- Organization
- Bounty amount
- Provider (Sphinx alias)
- Bounty Hunter (Sphinx alias)
- Bounty title
- Bounty link
- Bounty status
- Date assigned
- Date paid

### Acceptance Criteria
- [ ] I've submitted a screenshot of the export
- [ ] I've created a test that checks the order

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
Change order of columns in csv export

## Issue ticket number and link
closes #1421 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@wright-eric can you post a picture of the csv export and the columns that get displayed?

**Comment by wright-eric** [comment]
Screenshot from 2024-01-20 01-46-54
@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
LGTM! Let's get a code review.

**Comment by elraphty** [comment]
Nice Job @wright-eric.

**Comment by ecurrencyhodler** [comment]
Tested and looks good. Paid!

**Pull request merged**
