### PR TITLE
fix(#1260):added the test for history modal

### PR DESCRIPTION
**Pull request by Vayras**
With This PR I have added the test for historyModal
#1260

### CODE REVIEW

**Comment by elraphty** [comment]
@Vayras In your mock data, add the 3 payment types, payment, deposit, and withdraw

**Comment by elraphty** [comment]
@Vayras you also didn't test for these

- [ ] Test deposit does not have a receiver but has a sender
- [ ] Test that payment has a sender and a receiver

**Comment by Vayras** [comment]
> @Vayras In your mock data, add the 3 payment types, payment, deposit, and withdraw

Will Do

**Comment by Vayras** [comment]
> @Vayras you also didn't test for these
> 
> - [ ] Test deposit does not have a receiver but has a sender
> - [ ] Test that payment has a sender and a receiver
> 

Okay , Might have overlooked, I will update these as well

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
