### PR TITLE
Remove description default

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
Just added a condition
## Issue ticket number and link
https://github.com/stakwork/sphinx-tribes/issues/643

## Type of change
FrontEnd

## Checklist before requesting a review
- [✔️ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hi! are you on our bounties website? We actually have a bounty for this of 300,000 sats.

**Comment by kevkevinpal** [comment]
can you provide a video of this working @gouravmpk

**Comment by kevkevinpal** [comment]
So I think this is where the root of the problem is happening when we create a new user

https://github.com/stakwork/sphinx-tribes/blob/4cc379cf630aa21ae9261c260eef78df23b8907f/db/db.go#L122

it should be an empty string instead not sure why we added the word `description` in there

**Comment by gouravmpk** [comment]
image
If backend is sending description instead of empty string this solves it (Temp Fix) #992

**Comment by gouravmpk** [comment]
> can you provide a video of this working @gouravmpk

I have provided an I image #992 
please review
@kevkevinpal

**Comment by ecurrencyhodler** [comment]
Thanks for posting a screenshot @gouravmpk but can you post a video? This is one of items mentioned in the acceptance criteria:

"Post a video of you creating a profile, going to the people page, and showing that the profile description is not set to "description" by default."

**Comment by gouravmpk** [comment]
> Thanks for posting a screenshot @gouravmpk but can you post a video? This is one of items mentioned in the acceptance criteria:
> 
> "Post a video of you creating a profile, going to the people page, and showing that the profile description is not set to "description" by default."
Please check this out:

https://github.com/stakwork/sphinx-tribes/assets/20900042/155fdcfe-19ee-40fd-85b1-4a05bd913cf3

**Comment by ecurrencyhodler** [comment]
Thanks for posting a video. I didn't see your profile in it showing an empty profile description after you created the profile. Can you try again?

**Comment by gouravmpk** [comment]
https://github.com/stakwork/sphinx-tribes/assets/20900042/de772cd8-05a9-45a0-bc85-c1bf0ce3b279

@ecurrencyhodler do you mean like this ?

**Pull request closed without merging**
