### PR TITLE
fix(#1320):auto populate org

### PR DESCRIPTION
**Pull request by Vayras**
With this PR :
-Post bounty Modal auto populates the organization name
https://www.loom.com/share/e7323ceede244efd9b952b1c02820782?sid=82b6fce7-ef00-4a62-8220-c01447f7e3c8

--Notes On Current Implementation
the default value on the select comes from the api call getOrganizationByUuid , drop down values come from The Schema.ts file they act as mock organization data , alternatively we can call getOrganizationsById or create and alteranative function  getAllOrganizations that will populate this the dropdown , note the commented code in this PR on file FocusView.tsx references to dropDown option which is an empty array ,that can be used in the future to prefetch dropdown data from backend

this has been tested on chrome and firefox , implements #1320

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
all checks passed. Let's do a code review and discuss long term options for an implementation that vayras raised.

**Comment by ecurrencyhodler** [comment]
@elraphty this one has been sitting for a while. Can you take a look?

**Comment by ecurrencyhodler** [comment]
Hey Vayras. Just to give some context. Raph is taking his time reviewing this PR and testing it because it has the potential to break a lot of areas in our site. He'll update you when he's done.

**Comment by Vayras** [comment]
> Hey Vayras. Just to give some context. Raph is taking his time reviewing this PR and testing it because it has the potential to break a lot of areas in our site. He'll update you when he's done.

@ecurrencyhodler Thanks for your update , I will wait till Raph does the testing on this.

**Comment by elraphty** [comment]
@Vayras Tested, this breaks the add bounty dropdown, you used hardcoded organizations, organizations are dynamic, and each user's organizations defer, so it cannot be hardcoded.

**Comment by Vayras** [comment]
@elraphty Thanks for letting me know , I will update it with real organization values and update the PR

**Comment by Vayras** [comment]
https://www.loom.com/share/62ef6756679a41c2a690316c6c9e987c  @elraphty @ecurrencyhodler So I made some changes and can now see the list of the organization from backend as shown in the loom video , I cannot see the Bounties Platform Org in the list. The api endpoint I got the data from is `${TribesURL}/organizations`

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Comment by Vayras** [comment]
> Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

Sure , will do that , Thanks for your update

**Comment by Vayras** [comment]
@elraphty @ecurrencyhodler  I have update the workflow to get the value from backend here the video https://www.loom.com/share/6ef1ba861cd641dfa3d814e4ee66d52b

**Pull request closed without merging**
