### PR TITLE
Backend [Integration Test] tribes.go handlers GetTribe, CreateOrEditTribe, & GetTribeByUniqueName

### PR DESCRIPTION
**Pull request by FaisalIqbal211**
## Describe your changes

Implemented unit tests for tribes handlers to test GetTribe, CreateOrEditTribe and GetTribeByUniqueName methods

image
image

## Issue ticket number and link

Closes https://github.com/stakwork/sphinx-tribes/issues/1533

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by FaisalIqbal211** [comment]
**Note:** 

The first two scenarios (Should test that a tribe can be fetched by its uuid and Should test that a non-existent uuid returns no tribe) are already covered [here](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/tribes_test.go#L82-L149)

**Comment by AbdulWahab3181** [comment]
@FaisalIqbal211, I have reviewed the changes, and everything is perfect and working as expected. Great Job! @ecurrencyhodler, could you please approve the workflow? This will ensure that all test units are passing on GHA.

**Comment by elraphty** [comment]
please fix merge conflicts @FaisalIqbal211

**Comment by FaisalIqbal211** [comment]
@elraphty Done

**Comment by elraphty** [comment]
@FaisalIqbal211 you didn't test for this 
`
Should test that a tribe can be fetched by its uuid
Should test that a non-existent uuid returns no tribe
`

**Comment by FaisalIqbal211** [comment]
> @FaisalIqbal211 you didn't test for this
> 
> * Should test that a tribe can be fetched by its uuid
> * Should test that a non-existent uuid returns no tribe

@elraphty These scenarios are already covered. As you can see [here](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/tribes_test.go#L82-L149)

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1538

**Comment by FaisalIqbal211** [comment]
Thanks

**Pull request merged**
