### PR TITLE
fix(#1364):fixed filters not triggering

### PR DESCRIPTION
**Pull request by Vayras**
this PR will fix the filters not working issue

--Cause
lack of a toggle state for filters and mutation of the bounty array

--Fix
Enabled a toggle state and handled mutation

loom video:https://www.loom.com/share/14f895ad2f0040f9b5100d7bb244bab4

tested on chrome
test file updated

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@Vayras If you select multiple skills and unselect one of them, does it still work? You don't have to post a video. Just confirm.

**Comment by Vayras** [comment]
> @Vayras If you select multiple skills and unselect one of them, does it still work? You don't have to post a video. Just confirm.

@ecurrencyhodler  Yes , works correctly If you select and deselect multiple options at once

**Comment by ecurrencyhodler** [comment]
Great ty. Some jest tests are failing.

**Comment by Vayras** [comment]
> Great ty. Some jest tests are failing.

Just Fixing those

**Comment by ecurrencyhodler** [comment]
Tested. Works beautifully. Paid.

**Pull request merged**
