### PR TITLE
Test cases for MetricsBounties & MetricsBountiesCount

### LINKED ISSUE #1389: Backend [Integration Test] metrics.go handlers `MetricsBounties & MetricsBountiesCount`
### Context

We are trying to increase the test coverage for our Golang backend. 

### Design

Write tests for the metrics handlers, the test should:

- Return with a 401 if the pubkeyFromAuth is not decoded from the auth token
- Return a 406 error if a bad request is sent
- I should be able to get bounties within a specific date range
- I should be able to get the total count of bounties within a specific date range

FIle to test `metrics_test.go`

### Acceptance Criteria

We are trying to test that all tests pass

- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that 
- [ ] I've created tests with the appropriate data and they all pass
- [ ] I've tested that tests with the wrong data fails

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/bounty_test.go)

### PR DESCRIPTION
**Pull request by KumarNayan**
## Describe your changes
Test cases covering below scenarios 

Return with a 401 if the pubkeyFromAuth is not decoded from the auth token
Return a 406 error if a bad request is sent
I should be able to get bounties within a specific date range
I should be able to get the total count of bounties within a specific date range

## Issue ticket number and link
closes #1389 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by KumarNayan** [comment]
@elraphty

**Comment by ecurrencyhodler** [comment]
all checks passed. Let's get a code review.

**Comment by elraphty** [comment]
Please fix merge conflicts @KumarNayan

**Comment by KumarNayan** [comment]
> Please fix merge conflicts @KumarNayan

@elraphty resolved.

**Comment by ecurrencyhodler** [comment]
paid!

**Pull request merged**
