### PR TITLE
Mark as paid button flow and UI Fix

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
UI changes
## Issue ticket number and link
#1196
## Type of change

UI changes added some conditional rendering and some state management changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

## Video
Owner View

https://github.com/stakwork/sphinx-tribes/assets/20900042/20e7c779-f2a3-451f-b1d1-c6eb4eeaf01c

Organitation view with manage bounties access

https://github.com/stakwork/sphinx-tribes/assets/20900042/3ba96dba-619a-4b6e-8424-af73f7926ff0

Please go through the video and review the code I have included the banner and status hope this aligns with the desired outcome.
@ecurrencyhodler @kevkevinpal

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
How come you went with "Mark paid" vs. "mark as paid"? Is it due to sizing of the button? Same with "mark unpaid"?

You're missing the original "mark as paid" flow that is stipulated in the ticket. 

Logged in user who created bounty or is a user with the "manage bounty" permissions for that org should be taken through the same "paid bounty flow" as in desktop.
https://github.com/stakwork/sphinx-tribes/assets/32662508/64d444a6-ecad-4be4-9cc9-634c51489f7a

**Comment by gouravmpk** [comment]
> How come you went with "Mark paid" vs. "mark as paid"? Is it due to sizing of the button? Same with "mark unpaid"?
> 
> You're missing the original "mark as paid" flow that is stipulated in the ticket.
> 
> Logged in user who created bounty or is a user with the "manage bounty" permissions for that org should be taken through the same "paid bounty flow" as in desktop. https://github.com/stakwork/sphinx-tribes/assets/32662508/64d444a6-ecad-4be4-9cc9-634c51489f7a

@ecurrencyhodler it was my mistake I will add it "mark as paid"

**Comment by hritikmunde** [comment]
@ecurrencyhodler @gouravmpk and I are trying to set up my account but we are facing this issue.

image

**Comment by gouravmpk** [comment]
@ecurrencyhodler  I have updated the video please check also "Mark Paid" --> "Mark as Paid" 
and the organization access with manage bounty view

**Comment by kevkevinpal** [comment]
can you write a component test for `frontend/app/src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx` and assert that "Mark as Paid" button appears @gouravmpk

**Comment by gouravmpk** [comment]
@kevkevinpal @KumarNayan is working on the test for the same I think he has that bounty

**Comment by gouravmpk** [comment]
> frontend

@kevkevinpal @KumarNayan is writing test for this file he can handle it will it work he already is working on the bounty  ?

**Comment by kevkevinpal** [comment]
@gouravmpk I noticed some issues when I rebased your branch to master will push rebase one moment

**Comment by kevkevinpal** [comment]
Screenshot 2023-12-29 at 1 17 54 PM

**Comment by gouravmpk** [comment]
@kevkevinpal Is it not working ?

**Comment by kevkevinpal** [comment]
> @kevkevinpal Is it not working ?

I think test is failing is fine cause I just updated the percentages but please take a look at the picture I sent above

**Comment by gouravmpk** [comment]
> > @kevkevinpal Is it not working ?
> 
> I think test is failing is fine cause I just updated the percentages but please take a look at the picture I sent above

Yeah I checked let me run it locally and test

**Comment by gouravmpk** [comment]
I will retry yeah some issues popped up due to rebase
@kevkevinpal

**Pull request closed without merging**
