### PR TITLE
Feat✨: Added Load More button functionality to assigned bounties

### LINKED ISSUE #1074: Add a "load more" button to assigned tickets in profile
Currently, the assigned tickets only show 10 tickets. We should have the ability to view more using a "load more" button.
Screenshot 2023-12-11 at 9 20 38 AM

### Acceptance Criteria

- [ ] Tested on Chrome
- [ ] Posted a video of the load more button working
- [ ] Tests have passed.

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

1. Updated the visible tickets count to 20 
2. Added a Load More button 

## Issue ticket number and link
Closes #1074 

## Type of change

https://github.com/stakwork/sphinx-tribes/assets/91251535/372dbc34-82ec-49c5-8769-4c8b4c846046

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
LGTM! Nice change to show 20 at first. Let's get a code review. Also @VividhPandey003 could the initial # to show bounties affect other areas of the website like the homepage or viewing created bounties in the profile?

**Comment by VividhPandey003** [comment]
> LGTM! Nice change to show 20 at first. Let's get a code review. Also @VividhPandey003 could the initial # to show bounties affect other areas of the website like the homepage or viewing created bounties in the profile?

I don't think so. I could reverify this in local. Could you please explain it more

**Comment by ecurrencyhodler** [comment]
Check the home page to see how many bounties appear and see if it's 20 and if anything breaks. Currently I think it's 10. 

Also go to your profile and click "Bounties" tab and see how many get initially displayed. 

If the amount increases then that's no big deal. But if there's a breaking change, we should make some changes. Thanks!

**Comment by VividhPandey003** [comment]
> l. But if there's a breaking change, we should make some changes. Thanks!


https://github.com/stakwork/sphinx-tribes/assets/91251535/fdb5ba1e-f804-48c3-bf07-b6943b4869e3

**Comment by ecurrencyhodler** [comment]
Nice. Let's get a code review.

**Pull request merged**
