### PR TITLE
fix(#1013): created filter  for adminpage

### PR DESCRIPTION
**Pull request by kapildadhich075**
Added filters according to bounty status as per the issue and Figma design. 

Closes Issue No. #1013 .

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Please post a video of the filters you implemented as stated in the acceptance criteria.

Also you have 3 conflicts. Can you address those?

**Comment by elraphty** [comment]
Please fix the merge conflict  @kapildadhich075

**Comment by kapildadhich075** [comment]
https://github.com/stakwork/sphinx-tribes/assets/39085540/b2d9e000-e97c-490c-822c-aecaff4c899b

@ecurrencyhodler  here's the working of the filter. Let me go through to the issue, will resolve it

**Comment by ecurrencyhodler** [comment]
That looks pretty good! Thanks for doing that. 

Can you capitalize this section and the statuses if only one is selected?
- Open
- Assigned
- Completed
- Paid
Screenshot 2024-01-09 at 8 57 07 AM

**Comment by kevkevinpal** [comment]
if you could rebase your pr that would be good

**Pull request closed without merging**
