### PR TITLE
fix(#1013): fixed the Captial issue in Status Filter

### PR DESCRIPTION
**Pull request by kapildadhich075**
Added filters according to bounty status per the issue and Figma design and added Capitalize Status and try to resolve the conflicts

Closes Issue No. https://github.com/stakwork/sphinx-tribes/issues/1013 .

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Looks like you have build, prettier, jest tests that are failing. Can you address those?

**Comment by ecurrencyhodler** [comment]
your branch conflicts with these files:
frontend/app/src/pages/superadmin/tableComponent/index.tsx
frontend/app/src/pages/superadmin/tableComponent/mockBountyData.ts

Can you fix that?

**Comment by ecurrencyhodler** [comment]
You still have tests failing on build, prettier, and Jest.

**Comment by kapildadhich075** [comment]
I have committed again with an update can you check it?

**Comment by ecurrencyhodler** [comment]
Tests are still failing.

**Comment by ecurrencyhodler** [comment]
@elraphty do you think you can give some guidance to kapil?

**Comment by elraphty** [comment]
@kapildadhich075 The tests failing are from ` src/pages/superadmin/tableComponent/__tests__/TableComponent.spec.tsx  `, you have to make the TableComponent test work with your new changes.

**Comment by kapildadhich075** [comment]
@ecurrencyhodler I have updated the test file as ralph suggest me can you please check the workflow.  Let me know if something is lacking

**Comment by ecurrencyhodler** [comment]
Prettier and jest is failing.

**Comment by ecurrencyhodler** [comment]
@kapildadhich075 you also have some merge conflicts: 

frontend/app/src/pages/superadmin/accessDenied/index.tsx
frontend/app/src/pages/superadmin/header/index.tsx
frontend/app/src/pages/superadmin/tableComponent/__tests__/TableComponent.spec.tsx

Can you address these? Might need to rebase.

**Comment by ecurrencyhodler** [comment]
Closing this issue and assigning the bounty to someone else. We can find a different bounty for you later.

**Pull request closed without merging**
