### PR TITLE
Refactor `TestDeleteBot` To Use A Real Postgres DB For The Test

### PR DESCRIPTION
**Pull request by saithsab877**
## Describe your changes

image

## Issue ticket number and link

Closes: #1738

## Checklist before requesting a review
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by saithsab877** [comment]
Hi @elraphty, Please review this PR.

**Comment by elraphty** [comment]
@saithsab877 you are Abubakar on Sphinx Chat right?

**Comment by saithsab877** [comment]
> @saithsab877 you are Abubakar on Sphinx Chat, right?

Yes

**Comment by saithsab877** [comment]
> @saithsab877 you are Abubakar on Sphinx Chat, right?

@elraphty Yes

**Pull request merged**
