### PR TITLE
make second_brain_url updateable

### PR DESCRIPTION
**Pull request by Evanfeenstra**
## Describe your changes

make `second_brain_url` updateable

### CODE REVIEW

**Comment by tomsmith8** [comment]
@Evanfeenstra we good to merge this?

**Comment by elraphty** [comment]
> @Evanfeenstra we good to merge this?

I'm merging, It Looks Good To Me.

**Comment by tomsmith8** [comment]
Thanks, can you deploy these changes so I can check the functionality?

**Comment by elraphty** [comment]
> Thanks, can you deploy these changes so I can check the functionality?

Yeah, I will today with other changes.

**Pull request merged**
