### PR TITLE
enable bounty open on new window

### PR DESCRIPTION
**Pull request by Vayras**
This PR will enable bounty opening on new window , updating #1244 
--on clicking on bounty this take you to a new window

https://github.com/stakwork/sphinx-tribes/assets/89837102/10867091-f019-4572-b838-636825bb72dc

### CODE REVIEW

**Comment by Vayras** [comment]
@ecurrencyhodler added the PR

**Comment by elraphty** [comment]
@Vayras right-clicking on the bounty title does not show **OPEN IN A NEW TAB**, I think you should use a link tag to make this possible.

**Comment by Vayras** [comment]
> Contributor

okay will do

**Comment by Vayras** [comment]
added an anchor tag in place of the function this according to me will be a better implementation of the fix for this issue , it enable opening in new tab by default and also on right click shows OPEN IN NEW TAB just like @elraphty mentioned

**Comment by ecurrencyhodler** [comment]
Tested and it works. Gj Vayras! Paid. https://people-test.sphinx.chat/bounty/1056

**Pull request merged**
