### PR TITLE
display pagination by connection data to the backend

### LINKED ISSUE #1135: Enable pagination of bounties in superadmin
### Context
The bottom of the superadmin page has pagination for bounties that are displayed. The bounties that are displayed are set by the following:

- Date button on the very top right of the admin page
- Arrow button on the very top left of the admin page
- SortBy filter on the bounties section
- Status filter on the bounties section

Pagination must follow the logic of all the filters of the above when moving to the next page. Also only 20 bounties will be displayed for each page. Finally, below you can see the #'s 1-7. But you can go to 8+ if you click on the arrows.

Screenshot 2023-12-18 at 11 04 07 AM

**Full page**
Bounties V1 (5)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created tests for this feature.

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

Enable Pagination

## Issue ticket number and link

Closes #1135

Pagination Image

Pagination Image 2

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@elraphty are the api's enabled? Shouldn't we be able to see data now and paginate?

**Comment by elraphty** [comment]
> @elraphty are the APIs enabled? Shouldn't we be able to see data now and paginate?

Yeah, they are enabled, @gouravmpk Is working on displaying them, and doing them myself will be double work, currently I'm getting the total number of bounties in the last 30 days to display the pagination.

**Comment by Vayras** [comment]
> @elraphty are the api's enabled? Shouldn't we be able to see data now and paginate?

Yeah I have got the APIs working on the super admin page , will raise a PR soon

**Comment by Vayras** [comment]
> @Vayras I merged this to remove the mock data and use the data from the market, please pull and continue thanks.

Thanks @elraphty I will take the pull and finish working

**Comment by ecurrencyhodler** [comment]
@elraphty I'm getting some strange ux. Not sure if it's related to this PR or not. Probably not. But what do you think is the fix here?

1. I can only view pagination if I scale WAAYYY out
2. I can only see one # of the pagination instead of the expected 7


https://github.com/stakwork/sphinx-tribes/assets/32662508/c273e198-3f51-433c-b9d8-4f72c9f8f7de

**Comment by Vayras** [comment]
> @elraphty I'm getting some strange ux. Not sure if it's related to this PR or not. Probably not. But what do you think is the fix here?
> 
> 1. I can only view pagination if I scale WAAYYY out
> 2. I can only see one # of the pagination instead of the expected 7
> 
>  Pagination.mov

adding paginationLimit as dependency for getActiveTabs have fixed this issue for me and also setting the height of the section to 150px  as made it visible

**Pull request merged**
