### PR TITLE
Draft: Filters on homepage aren't working properly 

### LINKED ISSUE #1498: Filters on homepage aren't working properly
**Describe the bug**
Filters for skills aren't working properly on the home page. The status is working correctly however.

https://github.com/stakwork/sphinx-tribes/assets/32662508/0b3ac0d3-7584-441d-ae90-813d69b3e8d3

**Expected behavior**
Bounties with only the selected language and status should appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've included a test

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
Filters on homepage aren't working properly 

## Issue ticket number and link
closes #1498 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by wright-eric** [comment]
@ecurrencyhodler  would do some testing tomorrow and will give the MR for review then.

**Comment by ecurrencyhodler** [comment]
Can you post a video of selecting various skill filters locally from the home page?

**Comment by Vayras** [comment]
Hey! @wright-eric do you have an update on this issue?

**Comment by ecurrencyhodler** [comment]
@elraphty Let's review and merge tomorrow if:
1. eric doesn't respond by tomorrow
2. code and tests look good

If there are other issues, we can handle it outside of this PR

**Comment by ecurrencyhodler** [comment]
Eric said we can merge this if we want.

**Comment by elraphty** [comment]
> Eric said we can merge this if we want.

Tested, and merging

**Comment by ecurrencyhodler** [comment]
Paid 200k stats! https://community.sphinx.chat/bounty/1435

**Pull request merged**
