### PR TITLE
🐛 Fix: Enable filtering of skills on homepage

### LINKED ISSUE #987: Enable filtering of skills on homepage
**Describe the bug**
Currently, I am unable to view bounties on the bounty homepage if I select a filter of a skill. It works when I select a status.

https://github.com/stakwork/sphinx-tribes/assets/32662508/69268cfc-3d04-4740-8381-402cda617947

**Expected behavior**
When I select a skill in the filter, the page should dynamically display bounties that meet the criteria. The logic for this will be "and" instead of "or". This logic is different from the one specified in the people page in issue #986. So if multiple skills are selected, any bounty with any of the skills tagged should be displayed. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of me selecting one skill (javascript) in the filter and the homepage dynamically displaying the bounties
- [ ] I have posted a video of me selecting one skill (javascript + typescript) in the filter and the homepage dynamically displaying the bounties using "or" logic.

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes/assets/91251535/8c3dc1fb-e31a-4d8e-ac9b-1e4a3f3fc1bb

## Issue ticket number and link
Closes #987 

## Type of change

Fixes: 
1. Wrong var name was passed to the filter. 
2. Filter was not working as expected.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by VividhPandey003** [comment]
@kevkevinpal The tests are failing as the condition for validation is that it should return false. Could you please review this PR once.

Thanks for the help!!😄🚀

**Comment by kevkevinpal** [comment]
> @kevkevinpal The tests are failing as the condition for validation is that it should return false. Could you please review this PR once.
> 
> Thanks for the help!!😄🚀

ya looks like the failing test seems to actually be wrong if you can switch that to true then it should pass

**Comment by VividhPandey003** [comment]
@kevkevinpal Done with the test cases.

**Comment by ecurrencyhodler** [comment]
Tested and it works! Paying you out now.

**Pull request merged**
