### PR TITLE
Fix/deleted bounty

### PR DESCRIPTION
**Pull request by tobi-bams**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by tobi-bams** [comment]
@ecurrencyhodler, here is the demo

[demo](https://www.loom.com/share/57415466492b4ba68e2e99b7901e905a)

**Comment by ecurrencyhodler** [comment]
@tobi-bams you can delete a bounty by marking the bounty as "unpaid" on the bottom right, unassigning the hunter, and then deleting it.

**Comment by kevkevinpal** [comment]
ya we purposly make the delete button not appear when a bounty is paid maybe we can add some sort of on hover tool tip to let the user know they need to mark it as unpaid to delete the bounty but will close this PR for now

**Comment by ecurrencyhodler** [comment]
@tobi-bams even though this PR is closed, can you still address the issue #915 ?

@kevkevinpal I don't think we want to do that right now. Preserving completed bounties will be important for reconciliation in txn history for the org. 

We have it enabled for testing purposes.

**Comment by tobi-bams** [comment]
@kevkevinpal this PR addresses something else, could you please check the changes files to see the changes I made

The purpose of this PR was to fix the deleted bounty issue but I fixed something else alongside

**Comment by ecurrencyhodler** [comment]
Let's get another code review on this. Specifically around the issue of having the bounty popout in a separate window.

**Pull request merged**
