### PR TITLE
Fixed Org Scrolling 

### PR DESCRIPTION
**Pull request by Vayras**
#1277
Implemented Scrolling on Org page 
The scrolling on org work correctly now 
video:https://www.loom.com/share/1c2d554581c544829a129f7618588412
Tested on Chrome

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Great work! Video looks good. Can we add a test here so that the arrows correctly calls the next bounty on the org page when scrolling? Also a component test that an action happens when an arrow is clicked. 

I'll increase the bounty another 100k sats.

**Comment by ecurrencyhodler** [comment]
updated to 300k thanks: https://community.sphinx.chat/bounty/1242

**Comment by ecurrencyhodler** [comment]
All checks pass. Let's get a code review.

**Comment by Vayras** [comment]
@ecurrencyhodler Done

**Comment by elraphty** [comment]
Looking at it @Vayras, I may have to test for a while, just to be sure it breaks nothing

**Comment by Vayras** [comment]
> Looking at it @Vayras, I may have to test for a while, just to be sure it breaks nothing 

@elraphty Sure , Thanks for letting me know

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Comment by Vayras** [comment]
@ecurrencyhodler  done with resubmission of this PR , here is the link :https://github.com/stakwork/sphinx-tribes-frontend/pull/11

**Pull request closed without merging**
