### PR TITLE
added modal fix to new branch

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

On this PR, I fixed the user ticket modal pop-up bug.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ]

### CODE REVIEW

**Comment by kevkevinpal** [comment]
Seems like when I switch from "Assigned Tickets" to "Tickets" seems like it is opening the wrong ticket in the modal

**Comment by kevkevinpal** [comment]
Same when we're switching users, I think we're only refreshing that list when we're clicking assigned tickets

**Comment by kevkevinpal** [comment]
made a loom video to show what I mean

https://www.loom.com/share/f09f05f54e024424ac3834393ee34869

**Comment by ecurrencyhodler** [comment]
@elraphty is this pr still relevant? If not, can you close it?

**Pull request closed without merging**
