### PR TITLE
feat: implemented sort by newest and oldest

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
## Pull Request Description

- Implemented sort functionality by adding options to sort by newest and oldest
- Refactored the super admin logic by moving it into a reusable hook
- Extracted the `getBountyStatus` function into a utility folder, enhancing code organization. Additionally, tests have been added to ensure the correctness and reliability of the extracted function.

### Preview

https://www.loom.com/share/d8fd496cd9c645e4ba55dfaea29328a2?sid=baecdcdc-00dc-42fd-a755-9a968d65237e

### Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Okay there we go! all checks passed. Gj! Let's get a code review.

**Comment by elraphty** [comment]
@Ekep-Obasi the sort by and bounty status select dropdowns are not aligned, please fix this so I can merge your PR.
ALign Requirement

**Comment by Ekep-Obasi** [comment]
@elraphty please review

**Comment by elraphty** [comment]
> @elraphty please review

@Ekep-Obasi Sort By is still slightly higher than Status, I will suggest you put them in a flex box and align them

**Comment by Ekep-Obasi** [comment]
> > @elraphty please review
> 
> @Ekep-Obasi Sort By is still slightly higher than Status, I will suggest you put them in a flex box and align them

@elraphty you are right, I overlooked the alignment. It was actually in a flexbox  but the default elastic ui styles were the cause of this misalignment

This is a before 


And after ( this is the closest I could get)

**Comment by ecurrencyhodler** [comment]
tested. Was a big effort but you did it. GJ. Paying you out now!

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler thank you :)

**Pull request merged**
