### PR TITLE
fix(clear-search): Fixed Clear Search When Someone Clicks Out of The Page.

### PR DESCRIPTION
**Pull request by MirzaHanan**
### Problem:
The application retains the search term in the UI state when users navigate away from the profile page to either the `people page` or the `bounty homepage` and other `routes`. This behavior is inconsistent with typical user expectations where a search term should be cleared upon navigating to a different page.

### Expected Behavior:
When a user navigates away from the profile page, the search term entered should be automatically cleared. This ensures that when the user visits the `people` page or the `bounty homepage` and other `all routes`, they are presented with a fresh state, unfiltered by their previous search.

## Issue ticket number and link:
- **Ticket Number:** [ 1409 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes/issues/1409 ]

### Solution:
The solution involves adding an event listener in the `UiStore` class constructor to detect click events on the document. If a click event occurs outside the search input (`.search-input-wrapper`), the `clearSearchText` method is called to reset the `searchText` state to an empty string.

### Changes:
 - Modified the `UiStore` class constructor to include a document click event listener.
 - Implemented `handleDocumentClick`, a method to check the target of click events and determine if they occur outside the search input area.
 - Developed `clearSearchText` method to reset the search text.

### Evidence:
 Please see the attached video as evidence.
- Before Demo: [Link](https://www.loom.com/share/af20a272dc534e78bc40a559eb5a14f1)
- After Demo: [Link ](https://www.loom.com/share/2b1bbf712e334beaa3f3795b6cd1a72a)

### Testing:
- **Click-based Navigation**: Clicking on various elements and navigating to different pages to verify that the search term is cleared.
- **Keyboard Navigation**: Ensuring that non-click based navigations also result in the search term being cleared.
- **Edge Cases**: Testing with rapid navigation, back and forth between pages, and refreshing pages to observe the persistence of the search term.

### CODE REVIEW

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please review my this PR.

**Comment by ecurrencyhodler** [comment]
Video looks great. Good work! All checks passed. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Pull request closed without merging**
