### PR TITLE
updated status filter for accurate result

### PR DESCRIPTION
**Pull request by AbdulWahab3181**
## Describe your changes

https://github.com/stakwork/sphinx-tribes/assets/41957704/e28ea077-7db3-47ed-b81e-b4d4583bd055

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by AbdulWahab3181** [comment]
Hi @elraphty, could you please also merge this PR? This way, we will obtain more accurate results.

CC: @ecurrencyhodler

**Comment by elraphty** [comment]
@AbdulWahab3181 Please I will have to close this for now, please copy your changes, and I will alert you when you can make a new PR, your changes will add the frontend folder and sphinx-tribes.exe to the repo and we want to remove them from the repo's history.

**Comment by elraphty** [comment]
@AbdulWahab3181 you can pull the fresh master branch and make your changes, please ensure you are not making a push with the `fronted folder and sphinx-tribes.exe`

**Comment by AbdulWahab3181** [comment]
@elraphty Here is new PR https://github.com/stakwork/sphinx-tribes/pull/1476. Could you please review and merge it?

**Pull request closed without merging**
