### PR TITLE
Feat✨: Added dynamic placeholder text to Post A Bounty Modal

### LINKED ISSUE #1041: Add default text in bounty creation flow
Add the following text inside the description area when creating a bounty and if github selected:
Screenshot 2023-12-04 at 12 36 50 PM

----

Description *

_Provide some context and be as detailed as possible. The more information you provide the better. This will allow the hunter to have a fuller picture of the amount of work that is required to complete the task. Screenshots and screen recordings help a lot too!_ 

----

When you click into the box for the description, the text should disappear and the word "Description *" should float up and become the title of the box like you see in this video:

https://github.com/stakwork/sphinx-tribes/assets/32662508/1c04d832-c50e-4a4c-adc5-bee2414d1501

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of the text being visible and then disappearing when I click into the description

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes/assets/91251535/e45b25ba-ffdf-406e-9354-17591a390543

## Issue ticket number and link
Closes #1041 

## Type of change

1. **Added placeholder text to textarea input:**

- Description: Implemented a placeholder text for improved user guidance within the textarea input.
- Reasoning: Enhances user experience by providing context and expectations for the input field.

2. **Fixed the top spacing of placeholder:**

- Description: Adjusted the spacing of the placeholder text to ensure a visually polished appearance.
- Reasoning: Aesthetic improvement to maintain a consistent and appealing design.

3. **Placeholder text to only get displayed when github_description is not selected:**

- Description: Modified the behavior of the placeholder text to appear only when the github_description option is not selected.
- Reasoning: Aligns with the user interface logic, showing placeholder text relevant to the selected options.

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Beautiful thank you!!!! Really amazing work and great attention to detail. Let's do a code review.

**Comment by kevkevinpal** [comment]
@ecurrencyhodler might be more than needed we could populate the desc field when we hit the toggle with the actual desc from github if the link is valid aswell

**Comment by ecurrencyhodler** [comment]
That would be amazeballs. We should also add a feature to manually enlarge the size of the window as well to view the whole text.

**Comment by ecurrencyhodler** [comment]
Tested on staging. great work! Looks smooth. Paying you out now.

**Pull request merged**
