### PR TITLE
If backend is sending description instead of empty string this solves it (Temp Fix)

### PR DESCRIPTION
**Pull request by gouravmpk**
Describe your changes
 added a condition

Issue ticket number and link
https://github.com/stakwork/sphinx-tribes/issues/643

Type of change
FrontEnd
BackEnd

Checklist before requesting a review
[✔️ ] I have performed a self-review of my code
[✔️ ] Tested FrontEnd locally 

This will work didn't tested the backend locally
but as condition added in frontend its working !
image

### CODE REVIEW

**Comment by gouravmpk** [comment]
https://github.com/stakwork/sphinx-tribes/assets/20900042/de772cd8-05a9-45a0-bc85-c1bf0ce3b279

@ecurrencyhodler do you mean like this ? 
as you can see all the profile where description is written by default they are not showing anything this was the acceptance criteria according to what I understood please correct me if I am wrong

**Comment by ecurrencyhodler** [comment]
Okay that works. Thanks!

**Comment by gouravmpk** [comment]
#983
[✅ ]  I've tested the bounty creation process to make sure nothing has been broken
[✅ ] I've posted a screenshot displaying the asterisk 

and
 #988
[✅ ] I have tested on Chrome desktop
[✅ ] I have posted a video of creating a bounty without a github link in step 2 and it displaying an asterisk next to description. 
[✅ ] I have posted a video of creating a bounty with a github link in step 2 and there is no asterisk next to description.

Video:
https://github.com/stakwork/sphinx-tribes/assets/20900042/75bbbda4-5385-40f6-9121-d81cdc9918d4

@ecurrencyhodler @kevkevinpal I need to close this PR as all my changes are piling up in the same branch please verify and approve

**Comment by ecurrencyhodler** [comment]
LGTM. Great job. Let's get a code review.

**Comment by elraphty** [comment]
@gouravmpk please fix the prettier error by running ```yarn run prettier``` in the frontend/app folder, thanks.

**Comment by gouravmpk** [comment]
Sure

**Comment by gouravmpk** [comment]
[✅ ] yarn run prettier in the frontend/app

@elraphty

**Comment by elraphty** [comment]
@gouravmpk, I can still see the prettier errors, did you make any update on your text editor after running the prettier command?

**Comment by gouravmpk** [comment]
No! but let me run it again for confirmation

**Comment by elraphty** [comment]
> No! but let me run it again for confirmation

thanks.

**Comment by gouravmpk** [comment]
Can  you check now there were some unwanted changes in these 4 files by Prettier I reverted them back
@elraphty

**Comment by elraphty** [comment]
> Can you check now there were some unwanted changes in these 4 files by Prettier I reverted them back @elraphty

Okay, checking

**Comment by elraphty** [comment]
LOOKS GOOD TO ME.

**Comment by gouravmpk** [comment]
> LOOKS GOOD TO ME.
Nice 😃

**Comment by ecurrencyhodler** [comment]
I tested on staging by signing with an lnurl and confirmed I don't have the default "description" in my profile. Paying you out. Great job!

**Pull request merged**
