### PR TITLE
FIx Prod LNAUTH error

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

On this PR I fixed the error with lnurl auth on Prod.

## Issue ticket number and link

496 [https://github.com/stakwork/sphinx-tribes/issues/496]

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device

### CODE REVIEW

**Comment by kevkevinpal** [comment]
are you able to rebase your branch? looks like you have commits from two weeks ago here

I'm not exactly sure what the change to fix the issue was here

**Comment by elraphty** [comment]
> are you able to rebase your branch? looks like you have commits from two weeks ago here
> 
> I'm not exactly sure what the change to fix the issue was here

I pulled the master branch, and merged it with the lnurl_auth branch, the only change required was adding https:// to the default LNAUTH host i.e (https://people.sphinx.chat) instead of people.sphinx.chat

**Comment by kevkevinpal** [comment]
> > are you able to rebase your branch? looks like you have commits from two weeks ago here
> > I'm not exactly sure what the change to fix the issue was here
> 
> I pulled the master branch, and merged it with the lnurl_auth branch, the only change required was adding https:// to the default LNAUTH host i.e (https://people.sphinx.chat) instead of people.sphinx.chat

hmm I've already done that on the test server with the env var so I'm thinking that may not be the issue

**Comment by kevkevinpal** [comment]
also if you've pulled in the changes to your branch but it is still showing a diff on here that means its not fully synced

try doing 
`git fetch -a origin`
`git checkout master`
`git reset --hard origin/master`
then `git checkout -b branchname`

And then it should be synced up with master

**Comment by elraphty** [comment]
> > > are you able to rebase your branch? looks like you have commits from two weeks ago here
> > > I'm not exactly sure what the change to fix the issue was here
> > 
> > 
> > I pulled the master branch, and merged it with the lnurl_auth branch, the only change required was adding https:// to the default LNAUTH host i.e (https://people.sphinx.chat) instead of people.sphinx.chat
> 
> hmm I've already done that on the test server with the env var so I'm thinking that may not be the issue

On Prod, User's can't sign up with LNAUTh because the URL is not an absolute URL

**Comment by elraphty** [comment]
I'm closing the PR to create a new one

**Pull request closed without merging**
