### PR TITLE
Fix/1408 people search on person page

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes
Add hook for people searching in PeopleList component

## Issue ticket number and link
#1408 

## Type of change

New feature (non-breaking change which adds functionality)

https://jam.dev/c/fec834b3-6001-4e66-ba48-8230fa7358a5

### CODE REVIEW

**Comment by YLeight** [comment]
@ecurrencyhodler @elraphty I've moved source branch from main to fix branch due to fix other issues in parallel

**Comment by YLeight** [comment]
> > @ecurrencyhodler @elraphty I've moved source branch from main to fix branch due to fix other issues in parallel
> 
> Was the movement done on your forked repo?

Yes, I created this PR from the other branch in my fork

**Comment by YLeight** [comment]
The [old PR](https://github.com/stakwork/sphinx-tribes/pull/1427) was closed automatically

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Comment by YLeight** [comment]
@ecurrencyhodler https://github.com/stakwork/sphinx-tribes-frontend/pull/4

**Pull request closed without merging**
