### PR TITLE
Implemntation of skills filter on org homepage #1315

### PR DESCRIPTION
**Pull request by Vayras**
#1315
with this PR I have implemented the skills filter on org Homepage 
implementation involves modification of api call `getOrganizationBounties` and changes in frontend 
loom video:https://www.loom.com/share/685883cc25b74f8bae633b85a5d41a00
test have been updated
tested on chrome

### CODE REVIEW

**Comment by Vayras** [comment]
@elraphty  @ecurrencyhodler  modification of the `getOrganizationBounties` to accomadate filters is making it's test in `main.spec.ts`  to fail , but it's modification is the optimal and efficient way to filters , though we can handle that in the frontend as well , currently I have tried to fix the tests but that did not work. let me know your opinion on this, Thanks

**Comment by ecurrencyhodler** [comment]
Video looks good. Let's wait to see what raph has to say.

**Comment by elraphty** [comment]
@Vayras what modification are you proposing?

**Comment by Vayras** [comment]
> @Vayras what modification are you proposing?

slight modifications to query params , passing the language string which enables filtering by coding language making the getOrgBounties , work similar to getPeopleBounites

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by Vayras** [comment]
> Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

@ecurrencyhodler ofcourse ,will resubmit all the PRs related to frontend again on that repo

**Comment by Vayras** [comment]
Resubmission : https://github.com/stakwork/sphinx-tribes-frontend/pull/12

**Pull request closed without merging**
