### PR TITLE
added test for Mark as Unpaid button

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
Added test case (Don't merge)

## Issue ticket number and link
#1196

## Type of change
Unit test

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
You have some conflicting files @gouravmpk can you resolve?

**Comment by gouravmpk** [comment]
@ecurrencyhodler 
"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."
getting this message

**Comment by ecurrencyhodler** [comment]
Screenshot 2024-01-10 at 12 57 56 PM

**Comment by kevkevinpal** [comment]
looks good to me if you can resolve the merge conflict

**Comment by kevkevinpal** [comment]
@gouravmpk you can fix the merge conflict with `git rebase origin/master` and then solve the conflicts there

**Comment by elraphty** [comment]
The tests are not passing @gouravmpk

**Comment by ecurrencyhodler** [comment]
You've still got prettier and jest tests failing.

**Comment by gouravmpk** [comment]
> You've still got prettier and jest tests failing.

Yeah its not rendering in existing test because the button shows only when user is ORG admin or hasAccess
trying to figure it out

**Comment by gouravmpk** [comment]
@ecurrencyhodler , I've put in a lot of effort to write the test, but unfortunately, it seems to be facing issues due to conditional rendering. Despite trying every solution I could think of, the problem persists.

**Comment by ecurrencyhodler** [comment]
Hey thanks for the update. Let me sync with raph.

**Comment by ecurrencyhodler** [comment]
@gouravmpk we are going to close this PR and I will pay you out for the bounty. We are going to handle this separately in a different issue. Thanks for your attempt.

**Pull request closed without merging**
