### PR TITLE
PR: Reversal Payments Functionality

### LINKED ISSUE #1905: Implement Reversal after `Failed` payments

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

This PR Adds the payment reversal functionality.

## Issue ticket number and link

Closes #1905 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox

### CODE REVIEW

**Review by Evanfeenstra — COMMENTED** [review]
Can u help me understand what stops `ProcessReversePayments` from being called twice on the same failed payment?

**Comment by elraphty** [comment]
> Can u help me understand what stops `ProcessReversePayments` from being called twice on the same failed payment?



> Can u help me understand what stops `ProcessReversePayments` from being called twice on the same failed payment?

It only  reverses bounties payments that were PENDING then become FAILED after checking for payment status, If the bounty payment  has been paid, or failed it won't process reversal.

**Comment by Evanfeenstra** [comment]
can u link the specific line that stops the v2_payments_cron from being run twice on the same payment?

**Comment by elraphty** [comment]
> can u link the specific line that stops the v2_payments_cron from being run twice on the same payment?

https://github.com/stakwork/sphinx-tribes/pull/1936/files#diff-9149ba04ad6447f03cc0ba39d5c051944e26b65d7983cd1554125984da74c738L965-R978 Only pending payments go through

**Comment by elraphty** [comment]
> can u link the specific line that stops the v2_payments_cron from being run twice on the same payment?

This also gets only pending payments https://github.com/stakwork/sphinx-tribes/pull/1936/files#diff-1b0417ad22cdb9ca66636481007174e1ce62f773dd61df8fea67f4937712a376R16

**Comment by Evanfeenstra** [comment]
looks good, i get it now

Last thing is that if its just pending for a week, than we need to do the same thing. Lets do that in a differnet PR tho

**Pull request merged**
