### PR TITLE
fix(#1244):enable clicking on bounty

### LINKED ISSUE #1244: Enable clicking of bounties inside of super admin
### Context
Right now, bounties are unclickable in superadmin. What is expected is that when I right click on the bounty title, I should be able to open it up in a new window.

Screenshot 2024-01-03 at 3 17 40 PM

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a video recording of my PR

### PR DESCRIPTION
**Pull request by Vayras**
with this PR 
-Clicking on bounty take you the dedicated bounty page
-a subtle hover effect is added to the title as well

Changes made with fix
-Added onClick handler to the bounty and onClick calls an function that routes to the bounty page

loom video:https://www.loom.com/share/171a08e9304b430884034290764bb2b8?sid=128e3831-218b-42f1-a434-937aef3e3fab

tested on chrome and firefox
closes #1244

### CODE REVIEW

**Comment by kevkevinpal** [comment]
are you able to add an onclick test for the bounty text?

**Comment by Vayras** [comment]
> are you able to add an onclick test for the bounty text?

as in to include this on the test file?

**Comment by Vayras** [comment]
> are you able to add an onclick test for the bounty text?

done ,added the test

**Comment by ecurrencyhodler** [comment]
Hey @Vayras! I tested this on staging. The bounty should open in a new window as stated in the issue. Would you mind submitting another PR for that? Thanks!

**Comment by Vayras** [comment]
> Hey @Vayras! I tested this on staging. The bounty should open in a new window as stated in the issue. Would you mind submitting another PR for that? Thanks!

@ecurrencyhodler in a modal window on the same page instead of the routing? Let me know , I will surely raise another PR ,thanks

**Comment by ecurrencyhodler** [comment]
Something like this.
https://github.com/stakwork/sphinx-tribes/assets/32662508/2935cbe6-7f9b-4fb8-a4ce-5ff9e133d8e5

**Comment by Vayras** [comment]
> Something like this.
> https://github.com/stakwork/sphinx-tribes/assets/32662508/2935cbe6-7f9b-4fb8-a4ce-5ff9e133d8e5
> 
> 

Okay got it you want to open the same on another page got it thanks, will raise a PR soon

**Pull request merged**
