### PR TITLE
Add people search functionality to PeopleList component

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes
Add hook for people searching in PeopleList component

## Issue ticket number and link
#1408 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

https://jam.dev/c/fec834b3-6001-4e66-ba48-8230fa7358a5

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video looks great! Looks like prettier test is failing. Can you address that?

**Comment by YLeight** [comment]
> Video looks great! Looks like prettier test is failing. Can you address that?

Done

**Comment by ecurrencyhodler** [comment]
All checks passed. Let's do a code review.

**Comment by YLeight** [comment]
I’ve updated the PR.
I’ve realized complexity of the search functionality from People page and decided to simplify it
I've isolated a separate border hook, to simplify integration between components view and it's model for testing
This solution probably could be used for solving issues with people search on People page, @ecurrencyhodler I've sent you jams with them

**Comment by YLeight** [comment]
I'll appreciate any comments and suggestions 🙏

**Comment by YLeight** [comment]
Checking tests

**Comment by ecurrencyhodler** [comment]
This looks great! Thanks for the extra investigation. If @elraphty approves this approach, I'll add an extra 100k sats. Then I'll create another issue so you can apply it to the search on the people's page.

**Pull request closed without merging**
