### PR TITLE
fix: adjusted AddUserModal styles to address inconsistent width

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
### Describe your changes

Adjusted AddUserModal styles to address inconsistent width

### Preview 

https://www.loom.com/share/0e2d343ce4b24a099504a36d15989e9b?sid=22fb4086-d101-4531-82f1-ae9a66986ee8

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by elraphty** [comment]
LNAUTH USER

@Ekep-Obasi can you add an ellipsis for LNAUTH users, so they can also be selected, after adding a max-width the select button for them is not visible, thanks.

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi can you post another video after you've addressed Raph's comment?

**Comment by kevkevinpal** [comment]
Still seeing issues and not seeing elipsies (i.e. the ...) for the longer usernames

Screenshot 2023-12-30 at 11 19 36 AM
Screenshot 2023-12-30 at 11 19 41 AM

**Comment by Ekep-Obasi** [comment]
Screenshot (35)

**Pull request merged**
