### PR TITLE
fix/date format for Super Admin dashboard

### LINKED ISSUE #1357: Update date format in superadmin
### Context
Currently the date format in superadmin is a bit confusing because it has dashes:
Screenshot 2024-01-15 at 9 46 26 AM

### Design
Here's the [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9067%3A23134&mode=design&t=3o2Aa4RMHsuItjE2-1). Let's update it to the following format:
Screenshot 2024-01-15 at 9 49 13 AM

Let's update it to the following format if the year is different:
Screenshot 2024-01-15 at 9 46 21 AM

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr
- [ ] I've created a unit test that checks different years are displayed 

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

### PR DESCRIPTION
**Pull request by hritikmunde**
## Issue ticket number and link
closes #1357 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

## Date when both years are the same
image

## Date when both years are different
image

### CODE REVIEW

**Comment by hritikmunde** [comment]
@ecurrencyhodler , this is done please review changes. Also fixed previously written test for the latest format.

**Comment by ecurrencyhodler** [comment]
Nice looks good. Let's get a code review.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can you look into #1237 PR as well? It's failing prettier as the file is not formatted by default. Maybe we can add that into the exception.

**Comment by elraphty** [comment]
@hritikmunde please fix merge conflicts

**Comment by elraphty** [comment]
@hritikmunde the `src/pages/superadmin/header/__tests__/SuperAdminHeader.spec.tsx` are now faling, I guess you have to `yarn install`, it cannot find the variable `setShowCalendar`

**Comment by hritikmunde** [comment]
Are these changes from other PR? @elraphty the tests were passing before merge conflict.

**Comment by hritikmunde** [comment]
@elraphty @ecurrencyhodler this is done

**Comment by ecurrencyhodler** [comment]
Tested and it works. Paid!

**Pull request merged**
