### PR TITLE
Add Fields to Create Connection Modal and Integrate Backend Workflow

### PR DESCRIPTION
**Pull request by aliraza556**
## Closed: #2159

image

image

image

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by humansinstitute** [comment]
@tobi-bams can you look at this? 
@aliraza556 Looks like we have some test failures?

**Comment by aliraza556** [comment]
Hi @humansinstitute @tobi-bams,

Please review this PR. My unit tests have passed, but I suspect there might be a payment issue error, possibly related to the work @Evanfeenstra has been doing on this payment issue. Additionally, in this PR (https://github.com/stakwork/sphinx-tribes/pull/2166), there are no changes in the code, yet both the unit tests and Cypress tests have failed.

**Comment by aliraza556** [comment]
Hi @humansinstitute, @elraphty, Please review this PR.

**Comment by aliraza556** [comment]
Hi @humansinstitute Please review it here https://github.com/stakwork/sphinx-tribes/pull/2179

**Pull request closed without merging**
