### PR TITLE
test cases

### PR DESCRIPTION
**Pull request by KumarNayan**
Added test cases

[#1165](https://github.com/stakwork/sphinx-tribes/issues/1165)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by kevkevinpal** [comment]
if you can add a more descriptive title that would be helpful

**Comment by kevkevinpal** [comment]
looks like prettier job is failing
```
 [warn] src/pages/superadmin/accessDenied/AccessDenied.Spec.tsx
[warn] Code style issues found in the above file. Run Prettier to fix.
```

I wouldn't worry about this since its your first PR but if you run
`yarn run prettier` before committing it should solve that job

**Comment by kevkevinpal** [comment]
also one last thing is that if you're linking the issue add the key word closes before the issue number to auto close after merge like so

closes https://github.com/stakwork/sphinx-tribes/issues/1165

**Comment by kevkevinpal** [comment]
Nice work tho looking forward to more!

**Comment by KumarNayan** [comment]
Thanks @kevkevinpal I will take care of the points mentioned.

**Pull request merged**
