### PR TITLE
Redirect users to same page instead of home page

### PR DESCRIPTION
**Pull request by dranoid**
## Describe your changes
Users can now return to the page they were on before editing the bounty rather than going to the home page

## Issue ticket number and link
#850 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

### CODE REVIEW

**Comment by dranoid** [comment]
I tested it from profiles and the bounties home page but I couldn't test it as an organization

**Comment by ecurrencyhodler** [comment]
With this pr, anything that touches the modal is tied to the focus view and affects various aspects of the website. For example creation of bounty, assigning of bounty, and closing of a bounty. 

Before we review this PR and merge, we will need you do the following:
- [ ] I have tested creation of bounty on desktop (chrome)
- [ ] I have tested assigning of bounty on desktop (chrome)
- [ ] I have tested closing of bounty on desktop (chrome)
- [ ] I have tested creation of bounty on mobile (chrome)
- [ ] I have tested assigning of bounty on mobile (chrome)
- [ ] I have tested closing of bounty on mobile (chrome)

We will increase the bounty for this to 400,000 sats. Let me know what you think @dranoid

**Comment by dranoid** [comment]
Okay @ecurrencyhodler, I'll test the required items.

**Comment by ecurrencyhodler** [comment]
@dranoid awesome! I'll update the bounty.

**Comment by ecurrencyhodler** [comment]
@dranoid have you had a chance to do the testing? If so we can do a code review.

**Comment by dranoid** [comment]
Hey @ecurrencyhodler, this [commit](https://github.com/stakwork/sphinx-tribes/commit/2cd4348f40163f513458871767f07abd4ce5fcc5#diff-2a5bf3e8371549889acdaa81ae15b0ea65896b0ac7e6dfef2027a93a151e45c0) seems to have fixed the issue. Should I go ahead and close the PR?

**Comment by ecurrencyhodler** [comment]
Hey @dranoid yeah I'll close this PR. but I'll still award you 200k sats for the work you put in!

**Comment by dranoid** [comment]
Thank you very much @ecurrencyhodler

**Pull request closed without merging**
