### PR TITLE
fix:changed the fixed width for superadmin

### PR DESCRIPTION
**Pull request by Vayras**
changed the fixed width for superadmin

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Some context for this pr. 

https://github.com/stakwork/sphinx-tribes/pull/1085#issuecomment-1866785287

Let's get a code review then merge.

**Comment by Vayras** [comment]
@ecurrencyhodler , just have a commented a single line of code with this PR

**Comment by kevkevinpal** [comment]
@Vayras remove the yarn.lock from the commit diff

**Comment by aliraza556** [comment]
Hi @Vayras
 I've been working on stepping up through the project locally, but I'm facing some challenges and haven't been successful so far. Could you please share any relevant videos or resources that might assist me in successfully completing this step?

**Comment by aliraza556** [comment]
Hi @Vayras
 I've been working on stepping up through the project locally, but I'm facing some challenges and haven't been successful so far. Could you please share any relevant videos or resources that might assist me in successfully completing this step?

**Comment by Vayras** [comment]
> @Vayras remove the yarn.lock from the commit diff

Will do

**Comment by Vayras** [comment]
> Hi @Vayras I've been working on stepping up through the project locally, but I'm facing some challenges and haven't been successful so far. Could you please share any relevant videos or resources that might assist me in successfully completing this step?

Hey @aliraza556  can you Dm me on Sphinx Chat , I will try and help you

**Pull request closed without merging**
