### PR TITLE
feat: backend filter for skill and status

### LINKED ISSUE #1374: Implement backend filter for skills and status
### Context
The API call for homepage and org home page are different. We need to enable the same filtering code for the org homepage.

You can use the code we use for the frontend for the filtering for reference:
https://github.com/stakwork/sphinx-tribes/pull/1358

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
Implement backend filter for org bounties for skill and status

## Issue ticket number and link
close #1374 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox

### CODE REVIEW

**Comment by wright-eric** [comment]
Tested by connecting to local database,
Here is a sample response

curl 'http://localhost:5002/organizations/bounties/ck95pe04nncjnaefo08g?languages=Golang,React,Swift&limit=2' | jq .

```json
[
  {
    "bounty": {
      "id": 1070,
      "owner_id": "03b255bc52ad917a9eb5b19c9cb58211458f2129d1c4aca1c7fc29cc5cf74e8b7e",
      "paid": true,
      "show": true,
      "type": "freelance_job_request",
      "award": "",
      "assigned_hours": 0,
      "bounty_expires": "",
      "commitment_fee": 0,
      "price": 1,
      "title": "Test",
      "tribe": "none",
      "assignee": "03b255bc52ad917a9eb5b19c9cb58211458f2129d1c4aca1c7fc29cc5cf74e8b7e",
      "ticket_url": "https://github.com/stakwork/sphinx-tribes/issues/1254",
      "org_uuid": "",
      "description": "testing",
      "wanted_type": "Web development",
      "deliverables": "testing",
      "github_description": false,
      "one_sentence_summary": "",
      "estimated_session_length": "Less than 1 hour",
      "estimated_completion_date": "2024-01-06T17:35:34.769Z",
      "created": 1705121590,
      "updated": "2024-01-13T10:23:10.997757+05:30",
      "coding_languages": [
        "Typescript",
        "Swift"
      ]
    },
    "assignee": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "owner": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "organization": {
      "uuid": "",
      "name": "",
      "img": ""
    }
  },
  {
    "bounty": {
      "id": 1138,
      "owner_id": "021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b",
      "paid": false,
      "show": true,
      "type": "freelance_job_request",
      "award": "",
      "assigned_hours": 0,
      "bounty_expires": "",
      "commitment_fee": 0,
      "price": 200000,
      "title": "Add validation check for org name to be 120 characters or less",
      "tribe": "None",
      "assignee": "035f22835fbf55cf4e6823447c63df74012d1d587ed60ef7cbfa3e430278c44cce",
      "ticket_url": "https://github.com/stakwork/sphinx-tribes/issues/1322",
      "org_uuid": "ck95pe04nncjnaefo08g",
      "description": "### Context\r\nNow that we are revamping the org home page, we will need to set limits to org names so that it fits nicely within our designs. \r\n\r\n<img width=\"715\" alt=\"Screenshot 2024-01-09 at 12 30 45 PM\" src=\"https://github.com/stakwork/sphinx-tribes/assets/32662508/c93e4b65-c797-4a0c-add2-ca62ee273db0\">\r\n\r\nLet's limit the width to the description of an organization to 120 characters.\r\n\r\n### Design\r\n\r\n### Acceptance Criteria\r\n- [ ]  I've added a validation check that the length of an org name is 120 characters or less. If it greater than 120 then a response will be returned as \"Error: exceeds 120 character limit\".\r\n- [ ]  Create a unit test that checks if validation fails and passes",
      "wanted_type": "Dev ops",
      "deliverables": "",
      "github_description": true,
      "one_sentence_summary": "",
      "estimated_session_length": "",
      "estimated_completion_date": "2024-01-10T19:29:31.443Z",
      "created": 1704915122,
      "updated": "2024-01-11T01:02:02.089132+05:30",
      "coding_languages": [
        "Golang"
      ]
    },
    "assignee": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "owner": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "organization": {
      "uuid": "",
      "name": "",
      "img": ""
    }
  }
]


curl 'http://localhost:5002/organizations/bounties/ck1p7l6a5fdlqdgmmnpg?limit=2&Open=true' | jq .[].bounty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5312    0  5312    0     0   916k      0 --:--:-- --:--:-- --:--:-- 1037k
{
  "id": 1065,
  "owner_id": "022e1b77992ac596695fa3c72526c0aec3085ea35165ecc9e14273f100ded6ae99",
  "paid": false,
  "show": true,
  "type": "freelance_job_request",
  "award": "",
  "assigned_hours": 0,
  "bounty_expires": "",
  "commitment_fee": 0,
  "price": 300000,
  "title": "[Prompt Engineering] Select the most suitable entity based on the context. This is an open application and we will select the best submission.",
  "tribe": "None",
  "assignee": "",
  "ticket_url": "",
  "org_uuid": "ck1p7l6a5fdlqdgmmnpg",
  "description": "We are using ChatGPT4 to determine if an entity was possibly misinterpreted. The goal is to pick the entity from the list of candidates that would fit the context. We've provided the prompt we are currently using below, an example text to examine, and the result which led to an incorrect response. Your job is to provide a prompt that performs better than ours. You can change the parts of our prompt or write your own to accomplish the task.\n\n<b>Here is our current prompt: </b>\n\nGiven the possibly misinterpreted entity <mark>{ENTITY}</mark> that was mentioned in the following context <mark>{CONTEXT}</mark>, choose the entity that is the most likely correct transcription from the list provided. If none are likely the correct option, return the original entity.\n\nYour answer MUST be pronounced similarly to the original entity when spoken out loud.\n\nYou must also return a score from 1 to 10 of how confident you are in your choice. Your response must be in the format [\"choice\", \"confidence score (integer)\"]. Only include an the array in your response, no extra text. Here is the list of potential replacements: <mark>{LIST_OF_CANDIDATES}</mark>. Take a depth breathe and think step by step, do not make up your response.\n\n<hr>\n\n<b>An actual example: </b>\n<br>\n\nGiven the possibly misinterpreted entity <mark>\"Schumacher\"</mark> that was mentioned in the following context <mark>\" They can learn about TCAP and where we are and learn more about the organization. And then me personally, they can find me on LinkedIn. I'm Stacey and it's spelled Schumacher, like Michael Schumacher. No relation, unfortunately,\"</mark>, choose the entity that is the most likely correct transcription from the list provided. If none are likely the correct option, return the original entity. Your answer MUST be pronounced similarly to the original entity when spoken out loud. You must also return a score from 1 to 10 of how confident you are in your choice. Your response must be in the format [\"choice\", \"confidence score (integer)\"]. Only include an the array in your response, no extra text. Here is the list of potential replacements: <mark>[\"Michael Schumacher\",\"Alexander Schmacher\",\"Schumacher\",\"Tim Schumacher\",\"Kent Schumacher\"]</mark>. Take a depth breathe and think step by step, do not make up your response.\n\n<b>GPT4 Response:</b>\n[\"Michael Schumacher\", 10]\n<br>\n\nAs you can see it chose \"Michael Schumacher\" with a confidence score of 10 which is the wrong answer. If you read the context you will see that the correct answer is <mark>Schumacher</mark> because the entity in question is her Stacey's name and it is spelled correctly. The answer is present in the options as well.\n\n<hr>\n\n<h4>Acceptence Criteria</h4>\n<li><b>GPT should be able to choose the correct/option candidate for examples provided in the link below.</b></li>\n<li>GPT should be able to choose the correct candidate as long as it is present in the options each time.</li>\n<li>If the correct candidate is absent in the options, it should return the same entity.</li>\n<li>The input structure of the list of candidates needs to stay the same.</li>\n<li>The response structure needs to stay the same.</li>\n<br>\n\n<b>More example prompts are provided here:</b> https://docs.google.com/spreadsheets/d/1otUxfViNXzFVmXKqmrA1TGBy51qrENy87l0GrRU_1mk/edit?usp=sharing",
  "wanted_type": "Other",
  "deliverables": " ",
  "github_description": false,
  "one_sentence_summary": "",
  "estimated_session_length": "Less than 3 hours",
  "estimated_completion_date": "2024-01-07T16:38:13.390Z",
  "created": 1704749907,
  "updated": "2024-01-09T03:08:27.015198+05:30",
  "coding_languages": [
    "Other"
  ]
}```

### Test with status
curl 'http://localhost:5002/organizations/bounties/ck1p7l6a5fdlqdgmmnpg?limit=2&Open=true' | jq .

```json
[
  {
    "bounty": {
      "id": 1065,
      "owner_id": "022e1b77992ac596695fa3c72526c0aec3085ea35165ecc9e14273f100ded6ae99",
      "paid": false,
      "show": true,
      "type": "freelance_job_request",
      "award": "",
      "assigned_hours": 0,
      "bounty_expires": "",
      "commitment_fee": 0,
      "price": 300000,
      "title": "[Prompt Engineering] Select the most suitable entity based on the context. This is an open application and we will select the best submission.",
      "tribe": "None",
      "assignee": "",
      "ticket_url": "",
      "org_uuid": "ck1p7l6a5fdlqdgmmnpg",
      "description": "We are using ChatGPT4 to determine if an entity was possibly misinterpreted. The goal is to pick the entity from the list of candidates that would fit the context. We've provided the prompt we are currently using below, an example text to examine, and the result which led to an incorrect response. Your job is to provide a prompt that performs better than ours. You can change the parts of our prompt or write your own to accomplish the task.\n\n<b>Here is our current prompt: </b>\n\nGiven the possibly misinterpreted entity <mark>{ENTITY}</mark> that was mentioned in the following context <mark>{CONTEXT}</mark>, choose the entity that is the most likely correct transcription from the list provided. If none are likely the correct option, return the original entity.\n\nYour answer MUST be pronounced similarly to the original entity when spoken out loud.\n\nYou must also return a score from 1 to 10 of how confident you are in your choice. Your response must be in the format [\"choice\", \"confidence score (integer)\"]. Only include an the array in your response, no extra text. Here is the list of potential replacements: <mark>{LIST_OF_CANDIDATES}</mark>. Take a depth breathe and think step by step, do not make up your response.\n\n<hr>\n\n<b>An actual example: </b>\n<br>\n\nGiven the possibly misinterpreted entity <mark>\"Schumacher\"</mark> that was mentioned in the following context <mark>\" They can learn about TCAP and where we are and learn more about the organization. And then me personally, they can find me on LinkedIn. I'm Stacey and it's spelled Schumacher, like Michael Schumacher. No relation, unfortunately,\"</mark>, choose the entity that is the most likely correct transcription from the list provided. If none are likely the correct option, return the original entity. Your answer MUST be pronounced similarly to the original entity when spoken out loud. You must also return a score from 1 to 10 of how confident you are in your choice. Your response must be in the format [\"choice\", \"confidence score (integer)\"]. Only include an the array in your response, no extra text. Here is the list of potential replacements: <mark>[\"Michael Schumacher\",\"Alexander Schmacher\",\"Schumacher\",\"Tim Schumacher\",\"Kent Schumacher\"]</mark>. Take a depth breathe and think step by step, do not make up your response.\n\n<b>GPT4 Response:</b>\n[\"Michael Schumacher\", 10]\n<br>\n\nAs you can see it chose \"Michael Schumacher\" with a confidence score of 10 which is the wrong answer. If you read the context you will see that the correct answer is <mark>Schumacher</mark> because the entity in question is her Stacey's name and it is spelled correctly. The answer is present in the options as well.\n\n<hr>\n\n<h4>Acceptence Criteria</h4>\n<li><b>GPT should be able to choose the correct/option candidate for examples provided in the link below.</b></li>\n<li>GPT should be able to choose the correct candidate as long as it is present in the options each time.</li>\n<li>If the correct candidate is absent in the options, it should return the same entity.</li>\n<li>The input structure of the list of candidates needs to stay the same.</li>\n<li>The response structure needs to stay the same.</li>\n<br>\n\n<b>More example prompts are provided here:</b> https://docs.google.com/spreadsheets/d/1otUxfViNXzFVmXKqmrA1TGBy51qrENy87l0GrRU_1mk/edit?usp=sharing",
      "wanted_type": "Other",
      "deliverables": " ",
      "github_description": false,
      "one_sentence_summary": "",
      "estimated_session_length": "Less than 3 hours",
      "estimated_completion_date": "2024-01-07T16:38:13.390Z",
      "created": 1704749907,
      "updated": "2024-01-09T03:08:27.015198+05:30",
      "coding_languages": [
        "Other"
      ]
    },
    "assignee": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "owner": {
      "id": 0,
      "uuid": "",
      "owner_pubkey": "",
      "owner_alias": "",
      "unique_name": "",
      "description": "",
      "tags": null,
      "img": "",
      "created": null,
      "updated": null,
      "unlisted": false,
      "deleted": false,
      "last_login": 0,
      "owner_route_hint": "",
      "owner_contact_key": "",
      "price_to_meet": 0,
      "new_ticket_time": 0,
      "twitter_confirmed": false,
      "extras": null,
      "github_issues": null
    },
    "organization": {
      "uuid": "",
      "name": "",
      "img": ""
    }
  }
]
```

**Comment by wright-eric** [comment]
cc @ecurrencyhodler  @elraphty

**Comment by ecurrencyhodler** [comment]
all checks pass. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
