### PR TITLE
Admin owner alias

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
Changed Mapping 
## Issue ticket number and link
#1246
## Type of change
UI/Mapping
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by gouravmpk** [comment]
@ecurrencyhodler is this fine ?

https://github.com/stakwork/sphinx-tribes/assets/20900042/0db5a0d5-d6d1-4899-ad46-ee3c996704ef

**Comment by ecurrencyhodler** [comment]
Almost. The first letter of the alias's are all lowercase for providers. They should be capitalized.

**Comment by ecurrencyhodler** [comment]
Also you have some jest tests failing

**Comment by gouravmpk** [comment]
image
modified tests accordingly Idk why this test is failing

**Comment by gouravmpk** [comment]
@ecurrencyhodler here is the updated video also I will have to look in the test why is it failing but the test for checking the names of owner and provider are passing this is something different

https://github.com/stakwork/sphinx-tribes/assets/20900042/2cc335da-88f5-4d57-9888-fe8b6b83db35

**Comment by ecurrencyhodler** [comment]
LGTM! Let's get a code review. Good job.

**Comment by elraphty** [comment]
@gouravmpk Some of the assignee's alias are not capitalized Table Image

**Comment by gouravmpk** [comment]
It's coming in api response only I will add the cap functions there too

**Comment by elraphty** [comment]
> It's coming in api response only I will add the cap functions there too

Okay, thanks.

**Comment by gouravmpk** [comment]
> > It's coming in api response only I will add the cap functions there too
> 
> Okay, thanks.

I have made the change
@elraphty

**Comment by ecurrencyhodler** [comment]
tested and paid! Good job.

**Pull request merged**
