### PR TITLE
fix: setup loom sdk only when component mount

### PR DESCRIPTION
**Pull request by tobi-bams**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by tobi-bams** [comment]
@ecurrencyhodler I guess this PR solves the issue but I am not 100% sure as I was not able to test locally.

Setting up loom sandbox seemed impossible.

When this is merged and it does not solve the issue, please let me know Thanks

**Comment by ecurrencyhodler** [comment]
Okay sounds good. Let's get a review and merge. I'll test it on staging.

**Comment by elraphty** [comment]
I have tested it, it looks good to me, I'm merging.

**Comment by ecurrencyhodler** [comment]
I also tested. No more bug. Thanks @tobi-bams this was a really annoying one for users.

**Comment by tobi-bams** [comment]
> I also tested. No more bug. Thanks @tobi-bams this was a really annoying one for users.

yea!!!.... I am happy it worked!!

**Pull request merged**
