### PR TITLE
Description len check

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
added check for description 120 char 
added test
## Issue ticket number and link
#1322
## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by gouravmpk** [comment]
Hey @elraphty my tests are passing but failing due to coverage maybe .
image

**Comment by kevkevinpal** [comment]
> Hey @elraphty my tests are passing but failing due to coverage maybe .
> image
> 

I see this failing 

```
    --- FAIL: TestUnitCreateOrEditOrganization/should_successfully_add_organization_if_request_is_valid (0.00s)
```
You might need to add a desc to that test since this change adds a new requirement

**Comment by ecurrencyhodler** [comment]
All checks passed. Let's get a code review.

**Comment by gouravmpk** [comment]
Resolved @elraphty

**Comment by gouravmpk** [comment]
@elraphty  after resolving conflicts test is failing can you tell

**Comment by gouravmpk** [comment]
@elraphty fixed merge conflicts and breaking tests

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
