### PR TITLE
#1237 tests for OrganizatonView

### LINKED ISSUE #1237: [Tests][Component] Create test for people/widgetViews/OrganizationView.tsx
### Context

OrganizationView.tsx displays a user organization list.

File to be tested
`src/people/widgetViews/__tests__/OrganizationView.spec.tsx`

Create a file named
`src/people/widgetViews/__tests__/OrganizationView.spec.tsx`

The organizations listed on OrganizationView come from ```main. organizations ``

Make a Mock API request to get the user's organization and add data to ```main. organizations```, check ```getUserOrganizations``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```frontend/app/src/bounties/__tests__/bountyTest.spec.ts``` for example

We want to test that the organizations listed match the mocked data organizations

### Acceptance Criteria

- [ ] Test that user's organizations are visible
- [ ] Test that the name displayed matches the title from the mock data
- [ ] Test that the view bounties button is visible
- [ ] Test that the manage button is visible if the user is the owner of the organization
- [ ] Test that the manage button is hidden if the user is not the owner of the organization

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

### PR DESCRIPTION
**Pull request by hritikmunde**
## Issue ticket number and link
Closes #1237 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox

### CODE REVIEW

**Comment by hritikmunde** [comment]
@ecurrencyhodler @elraphty all tests are passed. Prettier is still failing after running before I push in `organization.ts` file

**Comment by hritikmunde** [comment]
@ecurrencyhodler any update on this?

**Comment by hritikmunde** [comment]
@elraphty any update on this?

**Comment by hritikmunde** [comment]
@elraphty , can you look into this?

**Comment by hritikmunde** [comment]
@elraphty @ecurrencyhodler , this is done.

**Comment by ecurrencyhodler** [comment]
All tests pass. GJ. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
paid!

**Pull request merged**
