### PR TITLE
PR: Add Last Withdrawal, and  Total Amount of Deposits Greater OR Equals Conditions

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

This PR adds a condition to check that the last budget withdrawal time is greater than 1 one, it  also checks that the sum of all the deposits In a workspace is greater than the sum of all withdrawals plus amount the user wants to withdraw

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox

### CODE REVIEW

**Review by Evanfeenstra — COMMENTED** [review]
Passing `getLightningInvoice` into `ProcessUpdateBudget` does not work. It must be part of the transaction in order to be atomic. I mean, it must use the `tx` to query

**Comment by elraphty** [comment]
> Passing `getLightningInvoice` into `ProcessUpdateBudget` does not work. It must be part of the transaction in order to be atomic. I mean, it must use the `tx` to query

Oh! thank @Evanfeenstra, I have made that change, can you please highlight the line, I tried searching locally but couldn't find it.

**Comment by Evanfeenstra** [comment]
you already made the other change previously. Go ahead and merge this PR @elraphty

**Comment by elraphty** [comment]
> you already made the other change previously. Go ahead and merge this PR @elraphty

Okay, nice

**Pull request merged**
