### PR TITLE
🐞Fix#1365:  Allow old bounties to be displayed

### LINKED ISSUE #1365: Allow old bounties to be displayed
**Describe the bug**
Some specific bounties such as the old ones most probably lead to a blank screen
image

https://github.com/stakwork/sphinx-tribes/assets/91251535/3fb51bb2-ec6a-4e2c-b089-1632c812e6ba

**To Reproduce**
1. Go to https://people.sphinx.chat/bounty/75 , https://people.sphinx.chat/bounty/252

**Expected behavior**
The bounty popup should appear

**REASON**
The reason might be that these are the old bounties which are already probably completed.
A quick fix to be to fix the frontend or to fix the database regarding these bounties still having open tag.

**Desktop (please complete the following information):**
 - Browser [Chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes/assets/91251535/9735f51d-bcda-418a-bf27-39b74145f9f7

## Issue ticket number and link

Closes #1365 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
All checks passed. Video checks out. Let's get a code review.

**Comment by elraphty** [comment]
@VividhPandey003 Closing the bounty Modal is buggy when looking at old bounties check this video out https://www.loom.com/share/0f84cc2b1c4d4d5e93e42312b44871b7

**Comment by VividhPandey003** [comment]
> @VividhPandey003 Closing the bounty Modal is buggy when looking at old bounties check this video out https://www.loom.com/share/0f84cc2b1c4d4d5e93e42312b44871b7

Oh. Let me fix it. Thanks @elraphty

**Comment by VividhPandey003** [comment]
@elraphty I am not able to recreate the bug.
i have tried in chrome. 
I searched the issue. Looks like this might be a firefox specific issue. 
image

Although I am still not able to reproduce this in firefox as well.

**Comment by ecurrencyhodler** [comment]
Hi! can you resubmit this PR to this new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
New api endpoint for our backend is: https://api.people-test.sphinx.chat/

**Pull request closed without merging**
