### PR TITLE
Add Webhook Endpoint and `ProcessTicketReview` Handler for Stackwork Ticket Review Automation

### PR DESCRIPTION
**Pull request by aliraza556**
### Describe the chnages:
- Implements webhook endpoint at `/bounty/ticket/review` to receive and process ticket updates from Stackwork workflows

closes: #1988

## Issue ticket number and link:
- **Ticket Number:** [ 1988 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes-frontend/issues/1988 ]

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] New feature (non-breaking change which adds functionality)
- [x] I have provided a screenshot of changes in my PR

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @humansinstitute, @elraphty,
Please review this PR.

**Review by tobi-bams — APPROVED** [review]
@aliraza556 please can you help resolve conflict

**Comment by aliraza556** [comment]
@tobi-bams Sure Just give me 2 mint.

**Comment by aliraza556** [comment]
Hi @tobi-bams, I have resolved the conflict. @humansinstitute. Please go ahead and merge it.

**Comment by elraphty** [comment]
Looks Good to me, I will merge it when the tests pass.

**Pull request merged**
