### PR TITLE
Make a user is able to post a bounty without a github link

### PR DESCRIPTION
**Pull request by maradondt**
## Describe your changes
Make user is able to post a bounty without a github link.
Disable the switch "Get Description From Github" when the link field is empty
## Issue ticket number and link
#424 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

### CODE REVIEW

**Comment by kevkevinpal** [comment]
Screen Shot 2023-03-01 at 10 10 14 AM

can we hide the `Get Description from github` toggle instead of just disable?

**Comment by maradondt** [comment]
@kevkevinpal yes, sure, I've done it

**Comment by kevkevinpal** [comment]
looking good but as I mentioned in the tribe we need to use the doCallToRelay function because otherwise we cant support tor and wireguard users

**Review by kevkevinpal — APPROVED** [review]
LGTM 🚀 

we'll need to write some tests and start refactoring since this change was difficult when it should have been pretty straight forward

**Pull request merged**
