### PR TITLE
Edit org flow

### LINKED ISSUE #776: Add edit organization flow
The starting point for this flow is in the admin org dashboard of a user who is logged in and looking at their own organization. To initiate this flow, they click "edit" on the top right.
My Profile - Organization Detail 8 59 06 AM

This is the modal they should see when they click "edit". If they tap on "delete", prompt the user with the screen below.
Edit Organization

Delete Organization - Warning

Here's the [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?type=design&node-id=7722%3A5505&mode=design&t=r1DIXNX0MXlqhgnr-1). 
[Prototype](https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?type=design&node-id=7722-5505&t=r1DIXNX0MXlqhgnr-0&scaling=min-zoom&page-id=7676%3A4080&starting-point-node-id=7761%3A5256&show-proto-sidebar=1)
Use dev mode: https://www.figma.com/dev-mode/

This is blocked by #772

### PR DESCRIPTION
**Pull request by cosmicpotato137**
## Describe your changes
Implementing the edit organization page.

## Issue ticket number and link
closes #776

## Type of change
New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

Screenshot 2023-10-20 164344

### CODE REVIEW

**Comment by cosmicpotato137** [comment]
I'm running into problems with editing the organization's name on the database, and I don't know how to push an image to the server. Is there an example in the codebase that I can see?

**Comment by ecurrencyhodler** [comment]
@elraphty do you have any guidance for Mac?

**Comment by kevkevinpal** [comment]
> I'm running into problems with editing the organization's name on the database, and I don't know how to push an image to the server. Is there an example in the codebase that I can see?

ya the backend code is in this same repo but this is the endpoint you'll be using if you want to edit a organization

[Backend Code for route](https://github.com/stakwork/sphinx-tribes/blob/master/routes/organizations.go#L24C39-L24C39)
[implementation of that endpoint](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/organizations.go#L17)

**Comment by elraphty** [comment]
> @elraphty do you have any guidance for Mac?

@ecurrencyhodler  there's no endpoint for updating an organization yet, I will create one for him.

**Comment by ecurrencyhodler** [comment]
Would he use the same endpoint to access the meme server for a profile image?

**Comment by kevkevinpal** [comment]
> > @elraphty do you have any guidance for Mac?
> 
> @ecurrencyhodler there's no endpoint for updating an organization yet, I will create one for him.

could he not use this endpoint @elraphty https://github.com/stakwork/sphinx-tribes/blob/master/routes/organizations.go#L24C39-L24C39

createOrEditOrganization?

**Comment by elraphty** [comment]
@cosmicpotato137 I added a new function in main.ts updateOrganization, pass the organization you want to update in this function, and it will update it.

**Comment by kevkevinpal** [comment]
> @cosmicpotato137 I added a new function in main.ts updateOrganization, pass the organization you want to update in this function, and it will update it.

Nice linking the commit 350bc5b868cb15e6a89d9355118df67846c05cf7

**Comment by cosmicpotato137** [comment]
> @cosmicpotato137 I added a new function in main.ts updateOrganization, pass the organization you want to update in this function, and it will update it.

Looking forward to learning how this all works :)

**Comment by ecurrencyhodler** [comment]
@kevkevinpal Do you know how Mac could access the meme server?

**Comment by kevkevinpal** [comment]
fixed merge conflict in [ab0a42a](https://github.com/stakwork/sphinx-tribes/pull/843/commits/ab0a42a89ffccb6a801b5ab6b48e41eb9a01b6b6)

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 if you keep an eye on #776, you'll see some code soon on how to interact with meme server.

**Comment by cosmicpotato137** [comment]
UI is finished!

**Pull request merged**
