### PR TITLE
Freeze bounty overview section

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
## Describe your changes

Freeze bounty overview on scroll using IntersectionObserver

- Intersection Observer: Used to trigger callback when scrolling past reference component.
- Custom Hook: useInViewPort encapsulates Intersection Observer logic for reusability.

Reason for Intersection Observer:

- CSS display: sticky; not applicable due to parent component's overflow property.

### Preview 

https://www.loom.com/share/54bd0f9dfbb845b8844285b484be078b?sid=3d78ad24-a21f-4a34-acd6-f9c1fa4af8a9

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Thanks for this pr! It's close but not quite right. when you scroll up, it should look like this design: 

Bounties V1 - Sticky Header (1)

It's missing sections like the title of each columns and the number of bounties. Also prettier is failing if you can fix that.

**Comment by Ekep-Obasi** [comment]
Thanks for the remark, 
Contrary to the design, the /admin page has some margins on both sides. How do I deal with that (keeping in mind that the title of each column has to align with the data in the table below it)?

<br />

sphinx admins

**Comment by ecurrencyhodler** [comment]
Do you have the latest? I think we removed the restricted width. This is what I see on staging right now.
Screenshot 2023-12-26 at 12 04 23 AM

**Comment by Ekep-Obasi** [comment]
That means I was working with the previous version 
Thanks @ecurrencyhodler 
Merry Christmas 💐

**Comment by ecurrencyhodler** [comment]
Merry Christmas! :)

**Comment by elraphty** [comment]
@Ekep-Obasi Please fix the prettier error by running ```yarn run prettier```

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler

https://www.loom.com/share/cdb3e2a05193450dab45bd5ced4a81ca?sid=c00f1cbc-cb66-4763-a6b0-b6fee64ad81f

**Comment by Ekep-Obasi** [comment]
> @Ekep-Obasi Please fix the prettier error by running `yarn run prettier`

I ran `yarn run prettier` but I don't know, it keeps failing in `src/hooks/useInViewport.ts`

I even targetted the file directly `npx prettier --config .prettierrc.json -w src/hooks/useInViewport.ts`

**Comment by ecurrencyhodler** [comment]
Nice! Looks a lot better. 

I see that there is a small glitch before the window freezes. Is there anyway you could address that?

https://github.com/stakwork/sphinx-tribes/assets/32662508/b2b90d77-7320-497b-a88f-5cf9f3ffd06e

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
 Yes I could fix that

**Comment by ecurrencyhodler** [comment]
That works. I think it can be smoother but we can handle that later. Let's do a code review.

**Comment by kevkevinpal** [comment]
looks like multiple jobs are failing and there are merge conflicts to be fixed

**Comment by kevkevinpal** [comment]
Compile error

```
Failed to compile.

TS2741: Property 'freezeHeaderRef' is missing in type '{}' but required in type 'StatisticProps'.
    38 |     ];
    39 |
  > 40 |     render(<Statistics />);
       |             ^^^^^^^^^^
    41 |     const bountiesPaid = screen.getAllByText('Bounties Paid');
    42 |     if (bountiesPaid) {
    43 |       expect(bountiesPaid[0]).toBeInTheDocument();
```

**Pull request closed without merging**
