### PR TITLE
feat: add extra properties while adding or editing org (description, website and github)

### LINKED ISSUE #1309: Enable create/edit org call to send 3 new fields to backend
### Context
Update endpoint to accept the three fields mentioned in #1307.

There are two diff. modals but designs are the same: Create organization and Edit organization.

Add organization: frontend/app/src/people/widgetViews/organization/AddOrganization.tsx

Edit organization: frontend/app/src/people/widgetViews/organization/EditOrgModal.tsx

Add website, github, and description field command to the body of the request.

And also populate website, github, and description inputs for edits.

 Also make sure to return error responses if any of the validation checks fail.

### Acceptance Criteria

- [ ] Add test for edit organization so that all values passed for org should be visible such as github, website, description if there is data. But if there is no org name the test should fail.
- [ ] Add test that checks that if save changes is clicked, a call is made.

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
added extra properties while adding or editing org  (description, website and github)

## Issue ticket number and link
close #1309 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by wright-eric** [comment]
cc @elraphty  @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Eric is this front end work? If so, I think these are handled separately in other issues.

**Comment by ecurrencyhodler** [comment]
Disregard my comment. All checks passed. Let's do a code review.

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
