### PR TITLE
Comma while typing sats amount

### PR DESCRIPTION
**Pull request by Marvel-Ib**
## Describe your changes
gave me a tougher time than i expected

I was able to do for the usd equivalent . but having trouble with the sats itself. 
@kevkevinpal  any tips?. the problem is the sat field is a number and all the validator about it requires it to be a number. so I am not really sure on how to go about that. 

https://github.com/stakwork/sphinx-tribes/assets/44719946/fcf7e6f1-bca4-4909-90d0-23a3a8fb137e

## Issue ticket number and link
#634 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

### CODE REVIEW

**Comment by Marvel-Ib** [comment]
@kevkevinpal   @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
@elraphty do you have any insight/suggestions you can provide here?

**Comment by Marvel-Ib** [comment]
@kevkevinpal  Sorry to disturb, still expecting help with this

**Comment by elraphty** [comment]
> @elraphty do you have any insight/suggestions you can provide here?

@ecurrencyhodler  I will take a look and merge today

**Comment by elraphty** [comment]
@Marvel-Ib change the number input to a text input, so you can format it, then convert it back to a number in FocusView.tsx before sending it to the backend.

**Comment by Marvel-Ib** [comment]
@elraphty  tricky but figured a way out, phew

@ecurrencyhodler  you can check the updated video to see if it matches what I was supposed to do.

**Comment by ecurrencyhodler** [comment]
Lgtm!! Great job.

**Comment by kevkevinpal** [comment]
added this commit to remove the usless if cause we can add a default value

[1a201e3](https://github.com/stakwork/sphinx-tribes/pull/790/commits/1a201e3f8f173917b45b8998f39d2b3d327b9f28)

**Pull request merged**
