### PR TITLE
Feat/org UI

### LINKED ISSUE #1330: Update "Add new org" ui
### Context
Now that we are revamping the org homepage, we need to add fields for description, website, and github repo. We will handle character restrictions in a separate issue. But implement the org name as a required field.

The backend may not be ready by the time this is completed which won't be an issue. 

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10359%3A25879&mode=design&t=YE6C1hFPCjMOCAhN-1). Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements.
Add New organisation (1)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot of the dashboard
- [ ] I've created a component test that the Organization Name text field appears
- [ ] I've created a component test that the website text field appears
- [ ] I've created a component test that the Github repo text field appears
- [ ] I've created a component test that the logo button appears
- [ ] I've created a component test that the description box appears
- [ ] I've created a component test that the Add Org button appears
- [ ] I've created a component test that when I click on Add Org button that an action happens.
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by KumarNayan**
## Describe your changes
Added new fields in add organization view and test cases

## Issue ticket number and link
closes #1330 

## Type of change
New fields in add org view and test cases

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend
Screenshot (47)

### CODE REVIEW

**Comment by KumarNayan** [comment]
cc : @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Hey @KumarNayan thanks for submitting the PR. It looks great for the most part. The boxes should be black though except when someone has clicked on it. It should turn black when it is no longer selected. You're also missing the 0/20 above the org name and 0/120 in the org description.

Let's also have the "add organization" turn blue once the Org Name has been filled as that's the only requirement.

**Comment by KumarNayan** [comment]
https://github.com/stakwork/sphinx-tribes/assets/66961974/458ede74-90d5-46cf-9d95-4de51b118524

Hey @ecurrencyhodler thanks for the review comments. I have attached the demo video with the changes. Please have a look if it looks fine.

**Comment by ecurrencyhodler** [comment]
Great work nayan! Can you double check to see if all sides of the description box turns blue? It looks like the left one is black.

Also sorry can we capitalize the R in Github Repo?

**Comment by KumarNayan** [comment]
> Great work nayan! Can you double check to see if all sides of the description box turns blue? It looks like the left one is black.
> 
> Also sorry can we capitalize the R in Github Repo?

@ecurrencyhodler I have made the R capital.
I think there is some issue with the video recording that I posted above. I can see all sides in blue color, attaching screenshot for reference.
Screenshot (284)

**Comment by ecurrencyhodler** [comment]
Okay then that's good. Let's get a code review!

**Comment by elraphty** [comment]
Great @KumarNayan, but it is not pixel-perfect, the width of the description and size of the inputs do not match the designs, please update and push so I can merge, thank you.

**Comment by elraphty** [comment]
Looks good to me

**Pull request merged**
