### PR TITLE
Replaced deleted bounty screen at urls when bounties have been deleted

### PR DESCRIPTION
**Pull request by gouravmpk**
## Describe your changes
Page added if user goes to deleted bounty from URL.

## Issue ticket number and link
https://github.com/stakwork/sphinx-tribes/issues/916

## Type of change
UI change page added if user goes to deleted bounty
Please delete options that are not relevant.

- [✅] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [✅] I have performed a self-review of my code
- [✅] I have tested on Chrome and Firefox
- [✅] I have tested on a mobile device
- [✅] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

## Recording

https://github.com/stakwork/sphinx-tribes/assets/20900042/1a47fc18-2835-4143-8b58-cf8d531f3e1f

Example:
http://localhost:3000/bounty/235
http://localhost:3000/bounty/623

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
This looks good! One small nit. Can we lower case the "B" in bounty? Thanks!

**Comment by gouravmpk** [comment]
> This looks good! One small nit. Can we lower case the "B" in bounty? Thanks!

Yep on It

**Comment by gouravmpk** [comment]
@kevkevinpal this PR

**Comment by gouravmpk** [comment]
Closing this creating a new PR

**Pull request closed without merging**
