### PR TITLE
chore: redesigned edit organization modal

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
### Type of change

Redesign edit organization modal 

### Preview 

Capture2

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
You have some jest test failing. Can you take another look?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler @elraphty 
Please can I have a code review

**Comment by ecurrencyhodler** [comment]
Tested. Looks good. Paid! Thanks.

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi this PR broke our bounty creation modal. Can you do a follow up and fix it?
Screenshot 2024-01-22 at 8 41 39 AM

**Comment by Ekep-Obasi** [comment]
> @Ekep-Obasi this PR broke our bounty creation modal. Can you do a follow up and fix it?
> 
> Screenshot 2024-01-22 at 8 41 39 AM
> 
> 
> 
> 

@ecurrencyhodler Sorry, let me address this

**Comment by ecurrencyhodler** [comment]
No worries. thank you.

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi I'm unable to save the org after editing. Can you take another look at this PR and submit it in the new frontend repo? https://github.com/stakwork/sphinx-tribes-frontend

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Sorry for the inconvenience 

Please make sure 
- that your organization Name is less than or equal to 20 characters 
- that your description is not more than 121 characters 
- Also your website url and GitHub url must be valid. 

I think it is failing because the API is responding with a status code of 400 ( BadRequest )

**Comment by ecurrencyhodler** [comment]
okay thanks. I'll create a separate issue.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
check this out 

https://www.loom.com/share/c37eaa803a634a76928260c86d19ca2b?sid=2b1f2024-e492-4a27-b31c-3bc0c0cfb7e3

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Maybe we could just display a better error message

**Comment by ecurrencyhodler** [comment]
Yea it's working in prod but not staging.

**Comment by Ekep-Obasi** [comment]
It worked for me locally and also on people-test

**Pull request merged**
