### PR TITLE
fix ability to unassign user

### LINKED ISSUE #659: Unable to unassign a bounty taker from a bounty
I am unable to unassign a bounty taker from a bounty. I tried clicking on the "x" next to the bounty taker as well as editing the bounty, removing the bounty taker, and saving it.

https://github.com/stakwork/sphinx-tribes/assets/32662508/b1fa60ee-5124-46ec-ab41-e302552d6a40

### PR DESCRIPTION
**Pull request by maradondt**
## Issue ticket number and link
closes #659 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device

### CODE REVIEW

**Comment by maradondt** [comment]
https://github.com/stakwork/sphinx-tribes/assets/25481891/79cda44d-4877-4f4b-baa0-dab114a4e032

**Comment by maradondt** [comment]
But I think it needs also a backend fix, because I have to set in assignee not empty value for it to work
`newBody.assignee = 'emptyid';`

**Comment by kevkevinpal** [comment]
> @kevkevinpal I think it needs also a backend fix, because I have to set in assignee not empty value for it to work `newBody.assignee = 'emptyid';`

ok I can open another issue to fix this on the backend but this works for now!

**Comment by ecurrencyhodler** [comment]
So I tested this in staging: https://people-test.sphinx.chat/tickets

The ticket now immediately disappears when I assign someone. Could that have been introduced in this PR?

https://github.com/stakwork/sphinx-tribes/assets/32662508/517e21c3-4811-4707-96ec-1e44a18ed6e4

**Comment by kevkevinpal** [comment]
> So I tested this in staging: https://people-test.sphinx.chat/tickets
> 
> The ticket now immediately disappears when I assign someone. Could that have been introduced in this PR?
> ticket.disappears.mov

looks like it worked on the test server for you maybe we should have it refresh and show on the top maybe the last updated field is not changing

**Comment by maradondt** [comment]
> The ticket now immediately disappears when I assign someone.
@ecurrencyhodler 
I didn't change the logic, everything works the same as before the fix, but if needed I can disable the modal close after the reassignment.

**Comment by ecurrencyhodler** [comment]
Okay. For some reason I thought the window persisted after someone was assigned. My apologies. Let me create a separate issue. Thanks.

**Pull request merged**
