### PR TITLE
Changed the "Edit bounty" window behavior when save is clicked.

### LINKED ISSUE #760: Close "Edit Bounty" window after clicking save. Return back to bounty with updated details.
Currently when we edit a bounty and click to save our changes, nothing happens. 
https://github.com/stakwork/sphinx-tribes/assets/32662508/da463fdb-b4c3-44b5-acb7-277a0b6536c6

We should return the user back to the bounty page with updated information

### PR DESCRIPTION
**Pull request by dranoid**
## Describe your changes
When the save button is clicked on the "Edit bounty" window, the user is taken to the bounties page to see the updated bounty.

## Issue ticket number and link
Closes #760 
Link to [issue]( https://github.com/stakwork/sphinx-tribes/issues/760)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] It has been deployed to people-test.sphinx.chat and tested by others

### CODE REVIEW

**Comment by elraphty** [comment]
@dranoid I can't seem to save a bounty after editing, can you look into this? and also move the organization's select input to the top of other inputs, thanks.

**Comment by ecurrencyhodler** [comment]
@elraphty I think the organization select input issue is not related to this PR. But @dranoid can you resolve the inability to save a bounty after editing?

**Comment by dranoid** [comment]
@ecurrencyhodler, I'll look into it

**Comment by Marvel-Ib** [comment]
hmm weird @elraphty  this pr works on my end and the bounty is saved

**Comment by kevkevinpal** [comment]
I'm not sure if just editing the description fails I was able to update the amount

**Comment by elraphty** [comment]
> hmm weird @elraphty this pr works on my end and the bounty is saved

Okay @dranoid let me take another look.

**Pull request merged**
