### PR TITLE
fix: url regression

### PR DESCRIPTION
**Pull request by Jeezman**
closes https://github.com/stakwork/sphinx-tribes/issues/998

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@elraphty jeezman thinks we should distinguish bounty urls inside the org. 

"I think thats what users will expect. And it signifies viewing bounties within the organization. It's also more maintainble and easier to write tests against."

What do you think?

**Comment by kevkevinpal** [comment]
> @elraphty jeezman thinks we should distinguish bounty urls inside the org.
> 
> "I think thats what users will expect. And it signifies viewing bounties within the organization. It's also more maintainble and easier to write tests against."
> 
> What do you think?

I agree idk what adding 'org' to the URL path does other than say there is a org attached to the bounty and most users don't even care what the URL looks like and its still a bounty and the id is still the exact same and this simplifies the code, I think this is a good change nice work @Jeezman 

@elraphty thoughts?

**Comment by ecurrencyhodler** [comment]
Tested and works great. Thanks Jeezman for the fast follow.

**Comment by kevkevinpal** [comment]
> Tested and works great. Thanks Jeezman for the fast follow.

did you test on staging? not sure if its updated yet

**Comment by ecurrencyhodler** [comment]
I did and I didn't see the org url path. I can double check again soon.

**Pull request merged**
